// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import "strconv"

type AchievementType int32

const (
	AchievementTypeUnlock AchievementType = 0
	AchievementTypeStep   AchievementType = 1
)

var EnumNamesAchievementType = map[AchievementType]string{
	AchievementTypeUnlock: "Unlock",
	AchievementTypeStep:   "Step",
}

var EnumValuesAchievementType = map[string]AchievementType{
	"Unlock": AchievementTypeUnlock,
	"Step":   AchievementTypeStep,
}

func (v AchievementType) String() string {
	if s, ok := EnumNamesAchievementType[v]; ok {
		return s
	}
	return "AchievementType(" + strconv.FormatInt(int64(v), 10) + ")"
}
