// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// AddressableWhiteListExcelDto represents a FlatBuffers table
type AddressableWhiteListExcelDto struct {
	fbsutils.FlatBuffer
	Id           int64    `json:"id"`
	FolderPath   []string `json:"folder_path"`
	ResourcePath []string `json:"resource_path"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *AddressableWhiteListExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableWhiteList"))
	}
	AddressableWhiteListExcelStart(b)
	AddressableWhiteListExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	AddressableWhiteListExcelStartFolderPathVector(b, len(t.FolderPath))
	for i := range len(t.FolderPath) {
		b.PrependUOffsetT(b.CreateString(t.FolderPath[len(t.FolderPath)-i-1]))
	}
	AddressableWhiteListExcelAddFolderPath(b, b.EndVector(len(t.FolderPath)))
	AddressableWhiteListExcelStartResourcePathVector(b, len(t.ResourcePath))
	for i := range len(t.ResourcePath) {
		b.PrependUOffsetT(b.CreateString(t.ResourcePath[len(t.ResourcePath)-i-1]))
	}
	AddressableWhiteListExcelAddResourcePath(b, b.EndVector(len(t.ResourcePath)))
	return AddressableWhiteListExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *AddressableWhiteListExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *AddressableWhiteListExcelDto) UnmarshalMessage(e *AddressableWhiteListExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableWhiteList"))
	}
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.FolderPath = make([]string, e.FolderPathLength())
	for i := range e.FolderPathLength() {
		t.FolderPath[i] = fbsutils.Convert(string(e.FolderPath(i)), t.FlatBuffer.TableKey)
	}
	t.ResourcePath = make([]string, e.ResourcePathLength())
	for i := range e.ResourcePathLength() {
		t.ResourcePath[i] = fbsutils.Convert(string(e.ResourcePath(i)), t.FlatBuffer.TableKey)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *AddressableWhiteListExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsAddressableWhiteListExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (AddressableWhiteListExcelDto) FlatDataName() string {
	return "AddressableWhiteListExcel"
}
