// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// AddressableBlackListExcelTableDto represents a FlatBuffers table
type AddressableBlackListExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []AddressableBlackListExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *AddressableBlackListExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableBlackList"))
	}
	var __offset_data_list flatbuffers.UOffsetT
	__nestedOffsets_data_list := make([]flatbuffers.UOffsetT, len(t.DataList))
	for i := range len(t.DataList) {
		t.DataList[i].InitKey(t.FlatBuffer.TableKey)
		__nestedOffsets_data_list[i] = t.DataList[i].MarshalModel(b)
	}
	AddressableBlackListExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		b.PrependUOffsetT(__nestedOffsets_data_list[len(t.DataList)-i-1])
	}
	__offset_data_list = b.EndVector(len(t.DataList))
	AddressableBlackListExcelTableStart(b)
	AddressableBlackListExcelTableAddDataList(b, __offset_data_list)
	return AddressableBlackListExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *AddressableBlackListExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *AddressableBlackListExcelTableDto) UnmarshalMessage(e *AddressableBlackListExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableBlackList"))
	}
	t.DataList = make([]AddressableBlackListExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(AddressableBlackListExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *AddressableBlackListExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsAddressableBlackListExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (AddressableBlackListExcelTableDto) FlatDataName() string {
	return "AddressableBlackListExcelTable"
}
