// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for a FlatBuffers schema.
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// AddressableBlackListExcelDto represents a FlatBuffers table.
type AddressableBlackListExcelDto struct {
	fbsutils.FlatBuffer
	ID           int64    `json:"id"`
	FolderPath   []string `json:"folder_path"`
	ResourcePath []string `json:"resource_path"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *AddressableBlackListExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableBlackList"))
	}
	var folderPathOffset flatbuffers.UOffsetT
	folderPathOffsets := make([]flatbuffers.UOffsetT, len(t.FolderPath))
	for i := range t.FolderPath {
		folderPathOffsets[i] = b.CreateString(fbsutils.Encode(t.FolderPath[i], t.FlatBuffer.TableKey))
	}
	AddressableBlackListExcelStartFolderPathVector(b, len(t.FolderPath))
	for i := len(folderPathOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(folderPathOffsets[i])
	}
	folderPathOffset = b.EndVector(len(t.FolderPath))
	var resourcePathOffset flatbuffers.UOffsetT
	resourcePathOffsets := make([]flatbuffers.UOffsetT, len(t.ResourcePath))
	for i := range t.ResourcePath {
		resourcePathOffsets[i] = b.CreateString(fbsutils.Encode(t.ResourcePath[i], t.FlatBuffer.TableKey))
	}
	AddressableBlackListExcelStartResourcePathVector(b, len(t.ResourcePath))
	for i := len(resourcePathOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(resourcePathOffsets[i])
	}
	resourcePathOffset = b.EndVector(len(t.ResourcePath))
	AddressableBlackListExcelStart(b)
	AddressableBlackListExcelAddId(b, fbsutils.Convert(t.ID, t.FlatBuffer.TableKey))
	AddressableBlackListExcelAddFolderPath(b, folderPathOffset)
	AddressableBlackListExcelAddResourcePath(b, resourcePathOffset)
	return AddressableBlackListExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *AddressableBlackListExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *AddressableBlackListExcelDto) UnmarshalMessage(e *AddressableBlackListExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AddressableBlackList"))
	}
	t.ID = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.FolderPath = make([]string, e.FolderPathLength())
	for i := 0; i < e.FolderPathLength(); i++ {
		t.FolderPath[i] = fbsutils.Convert(string(e.FolderPath(i)), t.FlatBuffer.TableKey)
	}
	t.ResourcePath = make([]string, e.ResourcePathLength())
	for i := 0; i < e.ResourcePathLength(); i++ {
		t.ResourcePath[i] = fbsutils.Convert(string(e.ResourcePath(i)), t.FlatBuffer.TableKey)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *AddressableBlackListExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsAddressableBlackListExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (AddressableBlackListExcelDto) FlatDataName() string {
	return "AddressableBlackListExcel"
}
