// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// AddressableBlackListExcelDto represents a FlatBuffers table
type AddressableBlackListExcelDto struct {
	fbsutils.FlatBuffer
	FolderPath   []string `json:"folder_path"`
	Id           int64    `json:"id"`
	ResourcePath []string `json:"resource_path"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *AddressableBlackListExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	AddressableBlackListExcelStart(b)
	AddressableBlackListExcelStartFolderPathVector(b, len(t.FolderPath))
	for i := range len(t.FolderPath) {
		b.PrependUOffsetT(fbsutils.Convert(b.CreateString(t.FolderPath[len(t.FolderPath)-i-1]), t.FlatBuffer.TableKey))
	}
	AddressableBlackListExcelAddFolderPath(b, b.EndVector(len(t.FolderPath)))
	AddressableBlackListExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	AddressableBlackListExcelStartResourcePathVector(b, len(t.ResourcePath))
	for i := range len(t.ResourcePath) {
		b.PrependUOffsetT(fbsutils.Convert(b.CreateString(t.ResourcePath[len(t.ResourcePath)-i-1]), t.FlatBuffer.TableKey))
	}
	AddressableBlackListExcelAddResourcePath(b, b.EndVector(len(t.ResourcePath)))
	return AddressableBlackListExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *AddressableBlackListExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishAddressableBlackListExcelBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *AddressableBlackListExcelDto) UnmarshalMessage(e *AddressableBlackListExcel) error {
	t.FolderPath = make([]string, e.FolderPathLength())
	for i := range e.FolderPathLength() {
		t.FolderPath[i] = string(e.FolderPath(i))
	}
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.ResourcePath = make([]string, e.ResourcePathLength())
	for i := range e.ResourcePathLength() {
		t.ResourcePath[i] = string(e.ResourcePath(i))
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *AddressableBlackListExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsAddressableBlackListExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (AddressableBlackListExcelDto) FlatDataName() string {
	return "AddressableBlackListExcel"
}
