// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddressableWhiteListExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsAddressableWhiteListExcel(buf []byte, offset flatbuffers.UOffsetT) *AddressableWhiteListExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddressableWhiteListExcel{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAddressableWhiteListExcel(buf []byte, offset flatbuffers.UOffsetT) *AddressableWhiteListExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddressableWhiteListExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AddressableWhiteListExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddressableWhiteListExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddressableWhiteListExcel) ResourcePath(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *AddressableWhiteListExcel) ResourcePathLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AddressableWhiteListExcel) FolderPath(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *AddressableWhiteListExcel) FolderPathLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AddressableWhiteListExcel) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AddressableWhiteListExcel) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func AddressableWhiteListExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AddressableWhiteListExcelAddResourcePath(builder *flatbuffers.Builder, resourcePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(resourcePath), 0)
}
func AddressableWhiteListExcelStartResourcePathVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AddressableWhiteListExcelAddFolderPath(builder *flatbuffers.Builder, folderPath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(folderPath), 0)
}
func AddressableWhiteListExcelStartFolderPathVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AddressableWhiteListExcelAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(2, id, 0)
}
func AddressableWhiteListExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
