// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// AssistEchelonTypeConvertExcelTableDto represents a FlatBuffers table
type AssistEchelonTypeConvertExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []AssistEchelonTypeConvertExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *AssistEchelonTypeConvertExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AssistEchelonTypeConvertExcelTable"))
	}
	AssistEchelonTypeConvertExcelTableStart(b)
	AssistEchelonTypeConvertExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	AssistEchelonTypeConvertExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return AssistEchelonTypeConvertExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *AssistEchelonTypeConvertExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishAssistEchelonTypeConvertExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *AssistEchelonTypeConvertExcelTableDto) UnmarshalMessage(e *AssistEchelonTypeConvertExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("AssistEchelonTypeConvertExcelTable"))
	}
	t.DataList = make([]AssistEchelonTypeConvertExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(AssistEchelonTypeConvertExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *AssistEchelonTypeConvertExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsAssistEchelonTypeConvertExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (AssistEchelonTypeConvertExcelTableDto) FlatDataName() string {
	return "AssistEchelonTypeConvertExcelTable"
}
