// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AttendanceRewardExcelTable struct {
	_tab flatbuffers.Table
}

func GetRootAsAttendanceRewardExcelTable(buf []byte, offset flatbuffers.UOffsetT) *AttendanceRewardExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AttendanceRewardExcelTable{}
	x.Init(buf, n+offset)
	return x
}

func FinishAttendanceRewardExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAttendanceRewardExcelTable(buf []byte, offset flatbuffers.UOffsetT) *AttendanceRewardExcelTable {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AttendanceRewardExcelTable{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAttendanceRewardExcelTableBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AttendanceRewardExcelTable) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AttendanceRewardExcelTable) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AttendanceRewardExcelTable) DataList(obj *AttendanceRewardExcel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AttendanceRewardExcelTable) DataListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AttendanceRewardExcelTableStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AttendanceRewardExcelTableAddDataList(builder *flatbuffers.Builder, dataList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dataList), 0)
}
func AttendanceRewardExcelTableStartDataListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AttendanceRewardExcelTableEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
