// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for a FlatBuffers schema.
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// CheatCodeListExcelDto represents a FlatBuffers table.
type CheatCodeListExcelDto struct {
	fbsutils.FlatBuffer
	ID         int64    `json:"id"`
	CheatCode  []string `json:"cheat_code"`
	InputTitle []string `json:"input_title"`
	Desc       string   `json:"desc"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *CheatCodeListExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("CheatCodeList"))
	}
	var cheatCodeOffset flatbuffers.UOffsetT
	cheatCodeOffsets := make([]flatbuffers.UOffsetT, len(t.CheatCode))
	for i := range t.CheatCode {
		cheatCodeOffsets[i] = b.CreateString(fbsutils.Encode(t.CheatCode[i], t.FlatBuffer.TableKey))
	}
	CheatCodeListExcelStartCheatCodeVector(b, len(t.CheatCode))
	for i := len(cheatCodeOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(cheatCodeOffsets[i])
	}
	cheatCodeOffset = b.EndVector(len(t.CheatCode))
	var inputTitleOffset flatbuffers.UOffsetT
	inputTitleOffsets := make([]flatbuffers.UOffsetT, len(t.InputTitle))
	for i := range t.InputTitle {
		inputTitleOffsets[i] = b.CreateString(fbsutils.Encode(t.InputTitle[i], t.FlatBuffer.TableKey))
	}
	CheatCodeListExcelStartInputTitleVector(b, len(t.InputTitle))
	for i := len(inputTitleOffsets) - 1; i >= 0; i-- {
		b.PrependUOffsetT(inputTitleOffsets[i])
	}
	inputTitleOffset = b.EndVector(len(t.InputTitle))
	descOffset := b.CreateString(fbsutils.Encode(t.Desc, t.FlatBuffer.TableKey))
	CheatCodeListExcelStart(b)
	CheatCodeListExcelAddId(b, fbsutils.Convert(t.ID, t.FlatBuffer.TableKey))
	CheatCodeListExcelAddCheatCode(b, cheatCodeOffset)
	CheatCodeListExcelAddInputTitle(b, inputTitleOffset)
	CheatCodeListExcelAddDesc(b, descOffset)
	return CheatCodeListExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *CheatCodeListExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *CheatCodeListExcelDto) UnmarshalMessage(e *CheatCodeListExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("CheatCodeList"))
	}
	t.ID = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.CheatCode = make([]string, e.CheatCodeLength())
	for i := 0; i < e.CheatCodeLength(); i++ {
		t.CheatCode[i] = fbsutils.Convert(string(e.CheatCode(i)), t.FlatBuffer.TableKey)
	}
	t.InputTitle = make([]string, e.InputTitleLength())
	for i := 0; i < e.InputTitleLength(); i++ {
		t.InputTitle[i] = fbsutils.Convert(string(e.InputTitle(i)), t.FlatBuffer.TableKey)
	}
	t.Desc = fbsutils.Convert(string(e.Desc()), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *CheatCodeListExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsCheatCodeListExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (CheatCodeListExcelDto) FlatDataName() string {
	return "CheatCodeListExcel"
}
