// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// CurrencyExcelTableDto represents a FlatBuffers table
type CurrencyExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []CurrencyExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *CurrencyExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("CurrencyTable"))
	}
	CurrencyExcelTableStart(b)
	CurrencyExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	CurrencyExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return CurrencyExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *CurrencyExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishCurrencyExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *CurrencyExcelTableDto) UnmarshalMessage(e *CurrencyExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("CurrencyTable"))
	}
	t.DataList = make([]CurrencyExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(CurrencyExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *CurrencyExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsCurrencyExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (CurrencyExcelTableDto) FlatDataName() string {
	return "CurrencyExcelTable"
}
