// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EmblemExcelTableDto represents a FlatBuffers table
type EmblemExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []EmblemExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *EmblemExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	EmblemExcelTableStart(b)
	EmblemExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	EmblemExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return EmblemExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *EmblemExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishEmblemExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *EmblemExcelTableDto) UnmarshalMessage(e *EmblemExcelTable) error {
	t.DataList = make([]EmblemExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(EmblemExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *EmblemExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsEmblemExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (EmblemExcelTableDto) FlatDataName() string {
	return "EmblemExcelTable"
}
