// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// EventContentTreasureExcelDto represents a FlatBuffers table
type EventContentTreasureExcelDto struct {
	fbsutils.FlatBuffer
	EventContentId      int64  `json:"event_content_id"`
	TitleLocalize       string `json:"title_localize"`
	LoopRound           int32  `json:"loop_round"`
	UsePrefabName       string `json:"use_prefab_name"`
	TreasureBgImagePath string `json:"treasure_bg_image_path"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *EventContentTreasureExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("EventContentTreasure"))
	}
	EventContentTreasureExcelStart(b)
	EventContentTreasureExcelAddEventContentId(b, fbsutils.Convert(t.EventContentId, t.FlatBuffer.TableKey))
	EventContentTreasureExcelAddTitleLocalize(b, fbsutils.Convert(b.CreateString(t.TitleLocalize), t.FlatBuffer.TableKey))
	EventContentTreasureExcelAddLoopRound(b, fbsutils.Convert(t.LoopRound, t.FlatBuffer.TableKey))
	EventContentTreasureExcelAddUsePrefabName(b, fbsutils.Convert(b.CreateString(t.UsePrefabName), t.FlatBuffer.TableKey))
	EventContentTreasureExcelAddTreasureBgImagePath(b, fbsutils.Convert(b.CreateString(t.TreasureBgImagePath), t.FlatBuffer.TableKey))
	return EventContentTreasureExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *EventContentTreasureExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishEventContentTreasureExcelBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *EventContentTreasureExcelDto) UnmarshalMessage(e *EventContentTreasureExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("EventContentTreasure"))
	}
	t.EventContentId = fbsutils.Convert(e.EventContentId(), t.FlatBuffer.TableKey)
	t.TitleLocalize = fbsutils.Convert(string(e.TitleLocalize()), t.FlatBuffer.TableKey)
	t.LoopRound = fbsutils.Convert(e.LoopRound(), t.FlatBuffer.TableKey)
	t.UsePrefabName = fbsutils.Convert(string(e.UsePrefabName()), t.FlatBuffer.TableKey)
	t.TreasureBgImagePath = fbsutils.Convert(string(e.TreasureBgImagePath()), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *EventContentTreasureExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsEventContentTreasureExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (EventContentTreasureExcelDto) FlatDataName() string {
	return "EventContentTreasureExcel"
}
