// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// FarmingDungeonLocationManageExcelTableDto represents a FlatBuffers table
type FarmingDungeonLocationManageExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []FarmingDungeonLocationManageExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *FarmingDungeonLocationManageExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FarmingDungeonLocationManage"))
	}
	FarmingDungeonLocationManageExcelTableStart(b)
	FarmingDungeonLocationManageExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	FarmingDungeonLocationManageExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return FarmingDungeonLocationManageExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *FarmingDungeonLocationManageExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *FarmingDungeonLocationManageExcelTableDto) UnmarshalMessage(e *FarmingDungeonLocationManageExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FarmingDungeonLocationManage"))
	}
	t.DataList = make([]FarmingDungeonLocationManageExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(FarmingDungeonLocationManageExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *FarmingDungeonLocationManageExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsFarmingDungeonLocationManageExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (FarmingDungeonLocationManageExcelTableDto) FlatDataName() string {
	return "FarmingDungeonLocationManageExcelTable"
}
