// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// FieldEvidenceExcelDto represents a FlatBuffers table
type FieldEvidenceExcelDto struct {
	fbsutils.FlatBuffer
	DescriptionLocalizeKey string `json:"description_localize_key"`
	DetailLocalizeKey      string `json:"detail_localize_key"`
	ImagePath              string `json:"image_path"`
	NameLocalizeKey        string `json:"name_localize_key"`
	UniqueId               int64  `json:"unique_id"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *FieldEvidenceExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FieldEvidence"))
	}
	FieldEvidenceExcelStart(b)
	FieldEvidenceExcelAddDescriptionLocalizeKey(b, fbsutils.Convert(b.CreateString(t.DescriptionLocalizeKey), t.FlatBuffer.TableKey))
	FieldEvidenceExcelAddDetailLocalizeKey(b, fbsutils.Convert(b.CreateString(t.DetailLocalizeKey), t.FlatBuffer.TableKey))
	FieldEvidenceExcelAddImagePath(b, fbsutils.Convert(b.CreateString(t.ImagePath), t.FlatBuffer.TableKey))
	FieldEvidenceExcelAddNameLocalizeKey(b, fbsutils.Convert(b.CreateString(t.NameLocalizeKey), t.FlatBuffer.TableKey))
	FieldEvidenceExcelAddUniqueId(b, fbsutils.Convert(t.UniqueId, t.FlatBuffer.TableKey))
	return FieldEvidenceExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *FieldEvidenceExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishFieldEvidenceExcelBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *FieldEvidenceExcelDto) UnmarshalMessage(e *FieldEvidenceExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FieldEvidence"))
	}
	t.DescriptionLocalizeKey = fbsutils.Convert(string(e.DescriptionLocalizeKey()), t.FlatBuffer.TableKey)
	t.DetailLocalizeKey = fbsutils.Convert(string(e.DetailLocalizeKey()), t.FlatBuffer.TableKey)
	t.ImagePath = fbsutils.Convert(string(e.ImagePath()), t.FlatBuffer.TableKey)
	t.NameLocalizeKey = fbsutils.Convert(string(e.NameLocalizeKey()), t.FlatBuffer.TableKey)
	t.UniqueId = fbsutils.Convert(e.UniqueId(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *FieldEvidenceExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsFieldEvidenceExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (FieldEvidenceExcelDto) FlatDataName() string {
	return "FieldEvidenceExcel"
}
