// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// FormationLocationExcelDto represents a FlatBuffers table
type FormationLocationExcelDto struct {
	fbsutils.FlatBuffer
	Id      int64     `json:"id"`
	GroupId int64     `json:"group_id"`
	SlotZ   []float32 `json:"slot_z"`
	SlotX   []float32 `json:"slot_x"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *FormationLocationExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FormationLocation"))
	}
	FormationLocationExcelStart(b)
	FormationLocationExcelAddId(b, fbsutils.Convert(t.Id, t.FlatBuffer.TableKey))
	FormationLocationExcelAddGroupId(b, fbsutils.Convert(t.GroupId, t.FlatBuffer.TableKey))
	FormationLocationExcelStartSlotZVector(b, len(t.SlotZ))
	for i := range len(t.SlotZ) {
		b.PrependFloat32(fbsutils.Convert(t.SlotZ[len(t.SlotZ)-i-1], t.FlatBuffer.TableKey))
	}
	FormationLocationExcelAddSlotZ(b, b.EndVector(len(t.SlotZ)))
	FormationLocationExcelStartSlotXVector(b, len(t.SlotX))
	for i := range len(t.SlotX) {
		b.PrependFloat32(fbsutils.Convert(t.SlotX[len(t.SlotX)-i-1], t.FlatBuffer.TableKey))
	}
	FormationLocationExcelAddSlotX(b, b.EndVector(len(t.SlotX)))
	return FormationLocationExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *FormationLocationExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishFormationLocationExcelBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *FormationLocationExcelDto) UnmarshalMessage(e *FormationLocationExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("FormationLocation"))
	}
	t.Id = fbsutils.Convert(e.Id(), t.FlatBuffer.TableKey)
	t.GroupId = fbsutils.Convert(e.GroupId(), t.FlatBuffer.TableKey)
	t.SlotZ = make([]float32, e.SlotZLength())
	for i := range e.SlotZLength() {
		t.SlotZ[i] = e.SlotZ(i)
	}
	t.SlotX = make([]float32, e.SlotXLength())
	for i := range e.SlotXLength() {
		t.SlotX[i] = e.SlotX(i)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *FormationLocationExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsFormationLocationExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (FormationLocationExcelDto) FlatDataName() string {
	return "FormationLocationExcel"
}
