// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// GroundModuleRewardExcelTableDto represents a FlatBuffers table
type GroundModuleRewardExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []GroundModuleRewardExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *GroundModuleRewardExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundModuleReward"))
	}
	var __offset_data_list flatbuffers.UOffsetT
	__nestedOffsets_data_list := make([]flatbuffers.UOffsetT, len(t.DataList))
	for i := range len(t.DataList) {
		t.DataList[i].InitKey(t.FlatBuffer.TableKey)
		__nestedOffsets_data_list[i] = t.DataList[i].MarshalModel(b)
	}
	GroundModuleRewardExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		b.PrependUOffsetT(__nestedOffsets_data_list[len(t.DataList)-i-1])
	}
	__offset_data_list = b.EndVector(len(t.DataList))
	GroundModuleRewardExcelTableStart(b)
	GroundModuleRewardExcelTableAddDataList(b, __offset_data_list)
	return GroundModuleRewardExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) UnmarshalMessage(e *GroundModuleRewardExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundModuleReward"))
	}
	t.DataList = make([]GroundModuleRewardExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(GroundModuleRewardExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsGroundModuleRewardExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (GroundModuleRewardExcelTableDto) FlatDataName() string {
	return "GroundModuleRewardExcelTable"
}
