// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// GroundExcelTableDto represents a FlatBuffers table
type GroundExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []GroundExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *GroundExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundExcelTable"))
	}
	GroundExcelTableStart(b)
	GroundExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	GroundExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return GroundExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *GroundExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishGroundExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *GroundExcelTableDto) UnmarshalMessage(e *GroundExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundExcelTable"))
	}
	t.DataList = make([]GroundExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(GroundExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *GroundExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsGroundExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (GroundExcelTableDto) FlatDataName() string {
	return "GroundExcelTable"
}
