// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// GroundModuleRewardExcelTableDto represents a FlatBuffers table
type GroundModuleRewardExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []GroundModuleRewardExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *GroundModuleRewardExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundModuleReward"))
	}
	GroundModuleRewardExcelTableStart(b)
	GroundModuleRewardExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	GroundModuleRewardExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return GroundModuleRewardExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishGroundModuleRewardExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) UnmarshalMessage(e *GroundModuleRewardExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("GroundModuleReward"))
	}
	t.DataList = make([]GroundModuleRewardExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(GroundModuleRewardExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *GroundModuleRewardExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsGroundModuleRewardExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (GroundModuleRewardExcelTableDto) FlatDataName() string {
	return "GroundModuleRewardExcelTable"
}
