// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KatakanaConvertExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsKatakanaConvertExcel(buf []byte, offset flatbuffers.UOffsetT) *KatakanaConvertExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KatakanaConvertExcel{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKatakanaConvertExcel(buf []byte, offset flatbuffers.UOffsetT) *KatakanaConvertExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KatakanaConvertExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KatakanaConvertExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KatakanaConvertExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KatakanaConvertExcel) Jp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KatakanaConvertExcel) Kr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func KatakanaConvertExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func KatakanaConvertExcelAddJp(builder *flatbuffers.Builder, jp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(jp), 0)
}
func KatakanaConvertExcelAddKr(builder *flatbuffers.Builder, kr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(kr), 0)
}
func KatakanaConvertExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
func (*KatakanaConvertExcel) Name() string {
	return "KatakanaConvertExcel"
}
