// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// KeyMappingExcelDto represents a FlatBuffers table
type KeyMappingExcelDto struct {
	fbsutils.FlatBuffer
	Id             string  `json:"id"`
	TargetKeyCode  string  `json:"target_key_code"`
	IconPositionY  float32 `json:"icon_position_y"`
	IsDisplay      bool    `json:"is_display"`
	IconScaleX     float32 `json:"icon_scale_x"`
	IsUsed         bool    `json:"is_used"`
	IgnorePosCheck bool    `json:"ignore_pos_check"`
	IsLongPress    bool    `json:"is_long_press"`
	IconScaleY     float32 `json:"icon_scale_y"`
	IconPositionX  float32 `json:"icon_position_x"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *KeyMappingExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("KeyMapping"))
	}
	KeyMappingExcelStart(b)
	KeyMappingExcelAddId(b, b.CreateString(fbsutils.Convert(t.Id, t.FlatBuffer.TableKey)))
	KeyMappingExcelAddTargetKeyCode(b, b.CreateString(fbsutils.Convert(t.TargetKeyCode, t.FlatBuffer.TableKey)))
	KeyMappingExcelAddIconPositionY(b, fbsutils.Convert(t.IconPositionY, t.FlatBuffer.TableKey))
	KeyMappingExcelAddIsDisplay(b, t.IsDisplay)
	KeyMappingExcelAddIconScaleX(b, fbsutils.Convert(t.IconScaleX, t.FlatBuffer.TableKey))
	KeyMappingExcelAddIsUsed(b, t.IsUsed)
	KeyMappingExcelAddIgnorePosCheck(b, t.IgnorePosCheck)
	KeyMappingExcelAddIsLongPress(b, t.IsLongPress)
	KeyMappingExcelAddIconScaleY(b, fbsutils.Convert(t.IconScaleY, t.FlatBuffer.TableKey))
	KeyMappingExcelAddIconPositionX(b, fbsutils.Convert(t.IconPositionX, t.FlatBuffer.TableKey))
	return KeyMappingExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *KeyMappingExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *KeyMappingExcelDto) UnmarshalMessage(e *KeyMappingExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("KeyMapping"))
	}
	t.Id = fbsutils.Convert(string(e.Id()), t.FlatBuffer.TableKey)
	t.TargetKeyCode = fbsutils.Convert(string(e.TargetKeyCode()), t.FlatBuffer.TableKey)
	t.IconPositionY = fbsutils.Convert(e.IconPositionY(), t.FlatBuffer.TableKey)
	t.IsDisplay = e.IsDisplay()
	t.IconScaleX = fbsutils.Convert(e.IconScaleX(), t.FlatBuffer.TableKey)
	t.IsUsed = e.IsUsed()
	t.IgnorePosCheck = e.IgnorePosCheck()
	t.IsLongPress = e.IsLongPress()
	t.IconScaleY = fbsutils.Convert(e.IconScaleY(), t.FlatBuffer.TableKey)
	t.IconPositionX = fbsutils.Convert(e.IconPositionX(), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *KeyMappingExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsKeyMappingExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (KeyMappingExcelDto) FlatDataName() string {
	return "KeyMappingExcel"
}
