// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatdata

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LocalizeSkillExcel struct {
	_tab flatbuffers.Table
}

func GetRootAsLocalizeSkillExcel(buf []byte, offset flatbuffers.UOffsetT) *LocalizeSkillExcel {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LocalizeSkillExcel{}
	x.Init(buf, n+offset)
	return x
}

func FinishLocalizeSkillExcelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLocalizeSkillExcel(buf []byte, offset flatbuffers.UOffsetT) *LocalizeSkillExcel {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LocalizeSkillExcel{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLocalizeSkillExcelBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LocalizeSkillExcel) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LocalizeSkillExcel) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LocalizeSkillExcel) Key() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LocalizeSkillExcel) MutateKey(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *LocalizeSkillExcel) NameKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeKr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) NameJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeJp() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) NameTh() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionTh() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeTh() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) NameTw() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionTw() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeTw() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) NameEn() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) DescriptionEn() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LocalizeSkillExcel) SkillInvokeLocalizeEn() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LocalizeSkillExcelStart(builder *flatbuffers.Builder) {
	builder.StartObject(16)
}
func LocalizeSkillExcelAddKey(builder *flatbuffers.Builder, key uint32) {
	builder.PrependUint32Slot(0, key, 0)
}
func LocalizeSkillExcelAddNameKr(builder *flatbuffers.Builder, nameKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nameKr), 0)
}
func LocalizeSkillExcelAddDescriptionKr(builder *flatbuffers.Builder, descriptionKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(descriptionKr), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeKr(builder *flatbuffers.Builder, skillInvokeLocalizeKr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(skillInvokeLocalizeKr), 0)
}
func LocalizeSkillExcelAddNameJp(builder *flatbuffers.Builder, nameJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(nameJp), 0)
}
func LocalizeSkillExcelAddDescriptionJp(builder *flatbuffers.Builder, descriptionJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(descriptionJp), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeJp(builder *flatbuffers.Builder, skillInvokeLocalizeJp flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(skillInvokeLocalizeJp), 0)
}
func LocalizeSkillExcelAddNameTh(builder *flatbuffers.Builder, nameTh flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(nameTh), 0)
}
func LocalizeSkillExcelAddDescriptionTh(builder *flatbuffers.Builder, descriptionTh flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(descriptionTh), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeTh(builder *flatbuffers.Builder, skillInvokeLocalizeTh flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(skillInvokeLocalizeTh), 0)
}
func LocalizeSkillExcelAddNameTw(builder *flatbuffers.Builder, nameTw flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(nameTw), 0)
}
func LocalizeSkillExcelAddDescriptionTw(builder *flatbuffers.Builder, descriptionTw flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(descriptionTw), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeTw(builder *flatbuffers.Builder, skillInvokeLocalizeTw flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(skillInvokeLocalizeTw), 0)
}
func LocalizeSkillExcelAddNameEn(builder *flatbuffers.Builder, nameEn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(nameEn), 0)
}
func LocalizeSkillExcelAddDescriptionEn(builder *flatbuffers.Builder, descriptionEn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(descriptionEn), 0)
}
func LocalizeSkillExcelAddSkillInvokeLocalizeEn(builder *flatbuffers.Builder, skillInvokeLocalizeEn flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(skillInvokeLocalizeEn), 0)
}
func LocalizeSkillExcelEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
