// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// ProtocolSettingExcelDto represents a FlatBuffers table
type ProtocolSettingExcelDto struct {
	fbsutils.FlatBuffer
	Inventory            bool                 `json:"inventory"`
	Currency             bool                 `json:"currency"`
	Protocol             string               `json:"protocol"`
	Mail                 bool                 `json:"mail"`
	OpenConditionContent OpenConditionContent `json:"open_condition_content"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *ProtocolSettingExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("ProtocolSetting"))
	}
	ProtocolSettingExcelStart(b)
	ProtocolSettingExcelAddInventory(b, t.Inventory)
	ProtocolSettingExcelAddCurrency(b, t.Currency)
	ProtocolSettingExcelAddProtocol(b, b.CreateString(fbsutils.Convert(t.Protocol, t.FlatBuffer.TableKey)))
	ProtocolSettingExcelAddMail(b, t.Mail)
	ProtocolSettingExcelAddOpenConditionContent(b, fbsutils.Convert(t.OpenConditionContent, t.FlatBuffer.TableKey))
	return ProtocolSettingExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *ProtocolSettingExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *ProtocolSettingExcelDto) UnmarshalMessage(e *ProtocolSettingExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("ProtocolSetting"))
	}
	t.Inventory = e.Inventory()
	t.Currency = e.Currency()
	t.Protocol = fbsutils.Convert(string(e.Protocol()), t.FlatBuffer.TableKey)
	t.Mail = e.Mail()
	t.OpenConditionContent = OpenConditionContent(fbsutils.Convert(int32(e.OpenConditionContent()), t.FlatBuffer.TableKey))
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *ProtocolSettingExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsProtocolSettingExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (ProtocolSettingExcelDto) FlatDataName() string {
	return "ProtocolSettingExcel"
}
