// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	"errors"
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// StatLevelInterpolationExcelTableDto represents a FlatBuffers table
type StatLevelInterpolationExcelTableDto struct {
	fbsutils.FlatBuffer
	DataList []StatLevelInterpolationExcelDto `json:"data_list"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *StatLevelInterpolationExcelTableDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("StatLevelInterpolationExcelTable"))
	}
	StatLevelInterpolationExcelTableStart(b)
	StatLevelInterpolationExcelTableStartDataListVector(b, len(t.DataList))
	for i := range len(t.DataList) {
		// The array should be reversed.
		b.PrependUOffsetT(t.DataList[len(t.DataList)-i-1].MarshalModel(b))
	}
	StatLevelInterpolationExcelTableAddDataList(b, b.EndVector(len(t.DataList)))
	return StatLevelInterpolationExcelTableEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *StatLevelInterpolationExcelTableDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishStatLevelInterpolationExcelTableBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *StatLevelInterpolationExcelTableDto) UnmarshalMessage(e *StatLevelInterpolationExcelTable) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("StatLevelInterpolationExcelTable"))
	}
	t.DataList = make([]StatLevelInterpolationExcelDto, e.DataListLength())
	for i := range e.DataListLength() {
		d := new(StatLevelInterpolationExcel)
		if !e.DataList(d, i) {
			return errors.New("failed to unmarshal data")
		}
		t.DataList[i].UnmarshalMessage(d)
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *StatLevelInterpolationExcelTableDto) Unmarshal(data []byte) error {
	root := GetRootAsStatLevelInterpolationExcelTable(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (StatLevelInterpolationExcelTableDto) FlatDataName() string {
	return "StatLevelInterpolationExcelTable"
}
