// Code generated by fbsgen. DO NOT EDIT.
// Package flatdata contains generated code for FlatBuffers schema
package flatdata

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// StringTestExcelDto represents a FlatBuffers table
type StringTestExcelDto struct {
	fbsutils.FlatBuffer
	Script    string   `json:"script"`
	Sentence1 string   `json:"sentence1"`
	String    []string `json:"string"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *StringTestExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("StringTestExcel"))
	}
	StringTestExcelStart(b)
	StringTestExcelAddScript(b, fbsutils.Convert(b.CreateString(t.Script), t.FlatBuffer.TableKey))
	StringTestExcelAddSentence1(b, fbsutils.Convert(b.CreateString(t.Sentence1), t.FlatBuffer.TableKey))
	StringTestExcelStartStringVector(b, len(t.String))
	for i := range len(t.String) {
		b.PrependUOffsetT(fbsutils.Convert(b.CreateString(t.String[len(t.String)-i-1]), t.FlatBuffer.TableKey))
	}
	StringTestExcelAddString(b, b.EndVector(len(t.String)))
	return StringTestExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *StringTestExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	FinishStringTestExcelBuffer(b, t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *StringTestExcelDto) UnmarshalMessage(e *StringTestExcel) error {
	if t.FlatBuffer.TableKey == nil {
		t.FlatBuffer.InitKey(fbsutils.CreateTableKey("StringTestExcel"))
	}
	t.Script = fbsutils.Convert(string(e.Script()), t.FlatBuffer.TableKey)
	t.Sentence1 = fbsutils.Convert(string(e.Sentence1()), t.FlatBuffer.TableKey)
	t.String = make([]string, e.StringLength())
	for i := range e.StringLength() {
		t.String[i] = string(e.String(i))
	}
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *StringTestExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsStringTestExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (StringTestExcelDto) FlatDataName() string {
	return "StringTestExcel"
}
