# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CharacterVoiceSubtitleExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CharacterVoiceSubtitleExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCharacterVoiceSubtitleExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CharacterVoiceSubtitleExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CharacterVoiceSubtitleExcel
    def LocalizeCvGroup(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def CharacterVoiceGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVoiceSubtitleExcel
    def Tlmid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVoiceSubtitleExcel
    def DurationKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CharacterVoiceSubtitleExcel
    def Separate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # CharacterVoiceSubtitleExcel
    def LocalizeKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def LocalizeJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def LocalizeTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def LocalizeTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CharacterVoiceSubtitleExcel
    def LocalizeEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CharacterVoiceSubtitleExcelStart(builder):
    builder.StartObject(11)

def Start(builder):
    CharacterVoiceSubtitleExcelStart(builder)

def CharacterVoiceSubtitleExcelAddLocalizeCvGroup(builder, localizeCvGroup):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(localizeCvGroup), 0)

def AddLocalizeCvGroup(builder, localizeCvGroup):
    CharacterVoiceSubtitleExcelAddLocalizeCvGroup(builder, localizeCvGroup)

def CharacterVoiceSubtitleExcelAddCharacterVoiceGroupId(builder, characterVoiceGroupId):
    builder.PrependInt64Slot(1, characterVoiceGroupId, 0)

def AddCharacterVoiceGroupId(builder, characterVoiceGroupId):
    CharacterVoiceSubtitleExcelAddCharacterVoiceGroupId(builder, characterVoiceGroupId)

def CharacterVoiceSubtitleExcelAddTlmid(builder, tlmid):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(tlmid), 0)

def AddTlmid(builder, tlmid):
    CharacterVoiceSubtitleExcelAddTlmid(builder, tlmid)

def CharacterVoiceSubtitleExcelAddDuration(builder, duration):
    builder.PrependInt64Slot(3, duration, 0)

def AddDuration(builder, duration):
    CharacterVoiceSubtitleExcelAddDuration(builder, duration)

def CharacterVoiceSubtitleExcelAddDurationKr(builder, durationKr):
    builder.PrependInt64Slot(4, durationKr, 0)

def AddDurationKr(builder, durationKr):
    CharacterVoiceSubtitleExcelAddDurationKr(builder, durationKr)

def CharacterVoiceSubtitleExcelAddSeparate(builder, separate):
    builder.PrependBoolSlot(5, separate, 0)

def AddSeparate(builder, separate):
    CharacterVoiceSubtitleExcelAddSeparate(builder, separate)

def CharacterVoiceSubtitleExcelAddLocalizeKr(builder, localizeKr):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(localizeKr), 0)

def AddLocalizeKr(builder, localizeKr):
    CharacterVoiceSubtitleExcelAddLocalizeKr(builder, localizeKr)

def CharacterVoiceSubtitleExcelAddLocalizeJp(builder, localizeJp):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(localizeJp), 0)

def AddLocalizeJp(builder, localizeJp):
    CharacterVoiceSubtitleExcelAddLocalizeJp(builder, localizeJp)

def CharacterVoiceSubtitleExcelAddLocalizeTh(builder, localizeTh):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(localizeTh), 0)

def AddLocalizeTh(builder, localizeTh):
    CharacterVoiceSubtitleExcelAddLocalizeTh(builder, localizeTh)

def CharacterVoiceSubtitleExcelAddLocalizeTw(builder, localizeTw):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(localizeTw), 0)

def AddLocalizeTw(builder, localizeTw):
    CharacterVoiceSubtitleExcelAddLocalizeTw(builder, localizeTw)

def CharacterVoiceSubtitleExcelAddLocalizeEn(builder, localizeEn):
    builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(localizeEn), 0)

def AddLocalizeEn(builder, localizeEn):
    CharacterVoiceSubtitleExcelAddLocalizeEn(builder, localizeEn)

def CharacterVoiceSubtitleExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return CharacterVoiceSubtitleExcelEnd(builder)


class CharacterVoiceSubtitleExcelT(object):

    # CharacterVoiceSubtitleExcelT
    def __init__(
        self,
        localizeCvGroup = None,
        characterVoiceGroupId = 0,
        tlmid = None,
        duration = 0,
        durationKr = 0,
        separate = False,
        localizeKr = None,
        localizeJp = None,
        localizeTh = None,
        localizeTw = None,
        localizeEn = None,
    ):
        self.localizeCvGroup = localizeCvGroup  # type: Optional[str]
        self.characterVoiceGroupId = characterVoiceGroupId  # type: int
        self.tlmid = tlmid  # type: Optional[str]
        self.duration = duration  # type: int
        self.durationKr = durationKr  # type: int
        self.separate = separate  # type: bool
        self.localizeKr = localizeKr  # type: Optional[str]
        self.localizeJp = localizeJp  # type: Optional[str]
        self.localizeTh = localizeTh  # type: Optional[str]
        self.localizeTw = localizeTw  # type: Optional[str]
        self.localizeEn = localizeEn  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        characterVoiceSubtitleExcel = CharacterVoiceSubtitleExcel()
        characterVoiceSubtitleExcel.Init(buf, pos)
        return cls.InitFromObj(characterVoiceSubtitleExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, characterVoiceSubtitleExcel):
        x = CharacterVoiceSubtitleExcelT()
        x._UnPack(characterVoiceSubtitleExcel)
        return x

    # CharacterVoiceSubtitleExcelT
    def _UnPack(self, characterVoiceSubtitleExcel):
        if characterVoiceSubtitleExcel is None:
            return
        self.localizeCvGroup = characterVoiceSubtitleExcel.LocalizeCvGroup()
        self.characterVoiceGroupId = characterVoiceSubtitleExcel.CharacterVoiceGroupId()
        self.tlmid = characterVoiceSubtitleExcel.Tlmid()
        self.duration = characterVoiceSubtitleExcel.Duration()
        self.durationKr = characterVoiceSubtitleExcel.DurationKr()
        self.separate = characterVoiceSubtitleExcel.Separate()
        self.localizeKr = characterVoiceSubtitleExcel.LocalizeKr()
        self.localizeJp = characterVoiceSubtitleExcel.LocalizeJp()
        self.localizeTh = characterVoiceSubtitleExcel.LocalizeTh()
        self.localizeTw = characterVoiceSubtitleExcel.LocalizeTw()
        self.localizeEn = characterVoiceSubtitleExcel.LocalizeEn()

    # CharacterVoiceSubtitleExcelT
    def Pack(self, builder):
        if self.localizeCvGroup is not None:
            localizeCvGroup = builder.CreateString(self.localizeCvGroup)
        if self.tlmid is not None:
            tlmid = builder.CreateString(self.tlmid)
        if self.localizeKr is not None:
            localizeKr = builder.CreateString(self.localizeKr)
        if self.localizeJp is not None:
            localizeJp = builder.CreateString(self.localizeJp)
        if self.localizeTh is not None:
            localizeTh = builder.CreateString(self.localizeTh)
        if self.localizeTw is not None:
            localizeTw = builder.CreateString(self.localizeTw)
        if self.localizeEn is not None:
            localizeEn = builder.CreateString(self.localizeEn)
        CharacterVoiceSubtitleExcelStart(builder)
        if self.localizeCvGroup is not None:
            CharacterVoiceSubtitleExcelAddLocalizeCvGroup(builder, localizeCvGroup)
        CharacterVoiceSubtitleExcelAddCharacterVoiceGroupId(builder, self.characterVoiceGroupId)
        if self.tlmid is not None:
            CharacterVoiceSubtitleExcelAddTlmid(builder, tlmid)
        CharacterVoiceSubtitleExcelAddDuration(builder, self.duration)
        CharacterVoiceSubtitleExcelAddDurationKr(builder, self.durationKr)
        CharacterVoiceSubtitleExcelAddSeparate(builder, self.separate)
        if self.localizeKr is not None:
            CharacterVoiceSubtitleExcelAddLocalizeKr(builder, localizeKr)
        if self.localizeJp is not None:
            CharacterVoiceSubtitleExcelAddLocalizeJp(builder, localizeJp)
        if self.localizeTh is not None:
            CharacterVoiceSubtitleExcelAddLocalizeTh(builder, localizeTh)
        if self.localizeTw is not None:
            CharacterVoiceSubtitleExcelAddLocalizeTw(builder, localizeTw)
        if self.localizeEn is not None:
            CharacterVoiceSubtitleExcelAddLocalizeEn(builder, localizeEn)
        characterVoiceSubtitleExcel = CharacterVoiceSubtitleExcelEnd(builder)
        return characterVoiceSubtitleExcel
