# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizeExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizeExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLocalizeExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LocalizeExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizeExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LocalizeExcel
    def Kr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeExcel
    def Jp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeExcel
    def Th(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeExcel
    def Tw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeExcel
    def En(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def LocalizeExcelStart(builder):
    builder.StartObject(6)

def Start(builder):
    LocalizeExcelStart(builder)

def LocalizeExcelAddKey(builder, key):
    builder.PrependUint32Slot(0, key, 0)

def AddKey(builder, key):
    LocalizeExcelAddKey(builder, key)

def LocalizeExcelAddKr(builder, kr):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(kr), 0)

def AddKr(builder, kr):
    LocalizeExcelAddKr(builder, kr)

def LocalizeExcelAddJp(builder, jp):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(jp), 0)

def AddJp(builder, jp):
    LocalizeExcelAddJp(builder, jp)

def LocalizeExcelAddTh(builder, th):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(th), 0)

def AddTh(builder, th):
    LocalizeExcelAddTh(builder, th)

def LocalizeExcelAddTw(builder, tw):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(tw), 0)

def AddTw(builder, tw):
    LocalizeExcelAddTw(builder, tw)

def LocalizeExcelAddEn(builder, en):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(en), 0)

def AddEn(builder, en):
    LocalizeExcelAddEn(builder, en)

def LocalizeExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return LocalizeExcelEnd(builder)


class LocalizeExcelT(object):

    # LocalizeExcelT
    def __init__(
        self,
        key = 0,
        kr = None,
        jp = None,
        th = None,
        tw = None,
        en = None,
    ):
        self.key = key  # type: int
        self.kr = kr  # type: Optional[str]
        self.jp = jp  # type: Optional[str]
        self.th = th  # type: Optional[str]
        self.tw = tw  # type: Optional[str]
        self.en = en  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        localizeExcel = LocalizeExcel()
        localizeExcel.Init(buf, pos)
        return cls.InitFromObj(localizeExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, localizeExcel):
        x = LocalizeExcelT()
        x._UnPack(localizeExcel)
        return x

    # LocalizeExcelT
    def _UnPack(self, localizeExcel):
        if localizeExcel is None:
            return
        self.key = localizeExcel.Key()
        self.kr = localizeExcel.Kr()
        self.jp = localizeExcel.Jp()
        self.th = localizeExcel.Th()
        self.tw = localizeExcel.Tw()
        self.en = localizeExcel.En()

    # LocalizeExcelT
    def Pack(self, builder):
        if self.kr is not None:
            kr = builder.CreateString(self.kr)
        if self.jp is not None:
            jp = builder.CreateString(self.jp)
        if self.th is not None:
            th = builder.CreateString(self.th)
        if self.tw is not None:
            tw = builder.CreateString(self.tw)
        if self.en is not None:
            en = builder.CreateString(self.en)
        LocalizeExcelStart(builder)
        LocalizeExcelAddKey(builder, self.key)
        if self.kr is not None:
            LocalizeExcelAddKr(builder, kr)
        if self.jp is not None:
            LocalizeExcelAddJp(builder, jp)
        if self.th is not None:
            LocalizeExcelAddTh(builder, th)
        if self.tw is not None:
            LocalizeExcelAddTw(builder, tw)
        if self.en is not None:
            LocalizeExcelAddEn(builder, en)
        localizeExcel = LocalizeExcelEnd(builder)
        return localizeExcel
