# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioScriptFunnelExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioScriptFunnelExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScenarioScriptFunnelExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScenarioScriptFunnelExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioScriptFunnelExcel
    def GroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptFunnelExcel
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioScriptFunnelExcel
    def FunnelId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ScenarioScriptFunnelExcelStart(builder):
    builder.StartObject(3)

def Start(builder):
    ScenarioScriptFunnelExcelStart(builder)

def ScenarioScriptFunnelExcelAddGroupId(builder, groupId):
    builder.PrependInt64Slot(0, groupId, 0)

def AddGroupId(builder, groupId):
    ScenarioScriptFunnelExcelAddGroupId(builder, groupId)

def ScenarioScriptFunnelExcelAddIndex(builder, index):
    builder.PrependInt64Slot(1, index, 0)

def AddIndex(builder, index):
    ScenarioScriptFunnelExcelAddIndex(builder, index)

def ScenarioScriptFunnelExcelAddFunnelId(builder, funnelId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(funnelId), 0)

def AddFunnelId(builder, funnelId):
    ScenarioScriptFunnelExcelAddFunnelId(builder, funnelId)

def ScenarioScriptFunnelExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScenarioScriptFunnelExcelEnd(builder)


class ScenarioScriptFunnelExcelT(object):

    # ScenarioScriptFunnelExcelT
    def __init__(
        self,
        groupId = 0,
        index = 0,
        funnelId = None,
    ):
        self.groupId = groupId  # type: int
        self.index = index  # type: int
        self.funnelId = funnelId  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        scenarioScriptFunnelExcel = ScenarioScriptFunnelExcel()
        scenarioScriptFunnelExcel.Init(buf, pos)
        return cls.InitFromObj(scenarioScriptFunnelExcel)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, scenarioScriptFunnelExcel):
        x = ScenarioScriptFunnelExcelT()
        x._UnPack(scenarioScriptFunnelExcel)
        return x

    # ScenarioScriptFunnelExcelT
    def _UnPack(self, scenarioScriptFunnelExcel):
        if scenarioScriptFunnelExcel is None:
            return
        self.groupId = scenarioScriptFunnelExcel.GroupId()
        self.index = scenarioScriptFunnelExcel.Index()
        self.funnelId = scenarioScriptFunnelExcel.FunnelId()

    # ScenarioScriptFunnelExcelT
    def Pack(self, builder):
        if self.funnelId is not None:
            funnelId = builder.CreateString(self.funnelId)
        ScenarioScriptFunnelExcelStart(builder)
        ScenarioScriptFunnelExcelAddGroupId(builder, self.groupId)
        ScenarioScriptFunnelExcelAddIndex(builder, self.index)
        if self.funnelId is not None:
            ScenarioScriptFunnelExcelAddFunnelId(builder, funnelId)
        scenarioScriptFunnelExcel = ScenarioScriptFunnelExcelEnd(builder)
        return scenarioScriptFunnelExcel
