# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Excel

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioCharacterNameExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioCharacterNameExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScenarioCharacterNameExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScenarioCharacterNameExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioCharacterNameExcel
    def SmallPortrait(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def SpinePrefabName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def Shape(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScenarioCharacterNameExcel
    def ProductionStep(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScenarioCharacterNameExcel
    def NameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NicknameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NicknameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NicknameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def CharacterName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioCharacterNameExcel
    def NameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NicknameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NicknameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioCharacterNameExcel
    def NameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ScenarioCharacterNameExcelStart(builder): builder.StartObject(15)
def Start(builder):
    return ScenarioCharacterNameExcelStart(builder)
def ScenarioCharacterNameExcelAddSmallPortrait(builder, smallPortrait): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(smallPortrait), 0)
def AddSmallPortrait(builder, smallPortrait):
    return ScenarioCharacterNameExcelAddSmallPortrait(builder, smallPortrait)
def ScenarioCharacterNameExcelAddSpinePrefabName(builder, spinePrefabName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spinePrefabName), 0)
def AddSpinePrefabName(builder, spinePrefabName):
    return ScenarioCharacterNameExcelAddSpinePrefabName(builder, spinePrefabName)
def ScenarioCharacterNameExcelAddShape(builder, shape): builder.PrependInt32Slot(2, shape, 0)
def AddShape(builder, shape):
    return ScenarioCharacterNameExcelAddShape(builder, shape)
def ScenarioCharacterNameExcelAddProductionStep(builder, productionStep): builder.PrependInt32Slot(3, productionStep, 0)
def AddProductionStep(builder, productionStep):
    return ScenarioCharacterNameExcelAddProductionStep(builder, productionStep)
def ScenarioCharacterNameExcelAddNameTw(builder, nameTw): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(nameTw), 0)
def AddNameTw(builder, nameTw):
    return ScenarioCharacterNameExcelAddNameTw(builder, nameTw)
def ScenarioCharacterNameExcelAddNicknameTw(builder, nicknameTw): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(nicknameTw), 0)
def AddNicknameTw(builder, nicknameTw):
    return ScenarioCharacterNameExcelAddNicknameTw(builder, nicknameTw)
def ScenarioCharacterNameExcelAddNicknameEn(builder, nicknameEn): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(nicknameEn), 0)
def AddNicknameEn(builder, nicknameEn):
    return ScenarioCharacterNameExcelAddNicknameEn(builder, nicknameEn)
def ScenarioCharacterNameExcelAddNicknameJp(builder, nicknameJp): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(nicknameJp), 0)
def AddNicknameJp(builder, nicknameJp):
    return ScenarioCharacterNameExcelAddNicknameJp(builder, nicknameJp)
def ScenarioCharacterNameExcelAddNameJp(builder, nameJp): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(nameJp), 0)
def AddNameJp(builder, nameJp):
    return ScenarioCharacterNameExcelAddNameJp(builder, nameJp)
def ScenarioCharacterNameExcelAddNameTh(builder, nameTh): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(nameTh), 0)
def AddNameTh(builder, nameTh):
    return ScenarioCharacterNameExcelAddNameTh(builder, nameTh)
def ScenarioCharacterNameExcelAddCharacterName(builder, characterName): builder.PrependUint32Slot(10, characterName, 0)
def AddCharacterName(builder, characterName):
    return ScenarioCharacterNameExcelAddCharacterName(builder, characterName)
def ScenarioCharacterNameExcelAddNameKr(builder, nameKr): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(nameKr), 0)
def AddNameKr(builder, nameKr):
    return ScenarioCharacterNameExcelAddNameKr(builder, nameKr)
def ScenarioCharacterNameExcelAddNicknameKr(builder, nicknameKr): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(nicknameKr), 0)
def AddNicknameKr(builder, nicknameKr):
    return ScenarioCharacterNameExcelAddNicknameKr(builder, nicknameKr)
def ScenarioCharacterNameExcelAddNicknameTh(builder, nicknameTh): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(nicknameTh), 0)
def AddNicknameTh(builder, nicknameTh):
    return ScenarioCharacterNameExcelAddNicknameTh(builder, nicknameTh)
def ScenarioCharacterNameExcelAddNameEn(builder, nameEn): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(nameEn), 0)
def AddNameEn(builder, nameEn):
    return ScenarioCharacterNameExcelAddNameEn(builder, nameEn)
def ScenarioCharacterNameExcelEnd(builder): return builder.EndObject()
def End(builder):
    return ScenarioCharacterNameExcelEnd(builder)