// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// CharacterVoiceSubtitleExcelDto represents a FlatBuffers table.
type CharacterVoiceSubtitleExcelDto struct {
	fbsutils.FlatBuffer
	LocalizeCvGroup       string `json:"localize_cv_group"`
	CharacterVoiceGroupID int64  `json:"character_voice_group_id"`
	Tlmid                 string `json:"tlmid"`
	Duration              int64  `json:"duration"`
	DurationKr            int64  `json:"duration_kr"`
	Separate              bool   `json:"separate"`
	LocalizeKr            string `json:"localize_kr"`
	LocalizeJp            string `json:"localize_jp"`
	LocalizeTh            string `json:"localize_th"`
	LocalizeTw            string `json:"localize_tw"`
	LocalizeEn            string `json:"localize_en"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *CharacterVoiceSubtitleExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	localizeCvGroupOffset := b.CreateString(t.LocalizeCvGroup)
	tlmidOffset := b.CreateString(t.Tlmid)
	localizeKrOffset := b.CreateString(t.LocalizeKr)
	localizeJpOffset := b.CreateString(t.LocalizeJp)
	localizeThOffset := b.CreateString(t.LocalizeTh)
	localizeTwOffset := b.CreateString(t.LocalizeTw)
	localizeEnOffset := b.CreateString(t.LocalizeEn)
	CharacterVoiceSubtitleExcelStart(b)
	CharacterVoiceSubtitleExcelAddLocalizeCvGroup(b, localizeCvGroupOffset)
	CharacterVoiceSubtitleExcelAddCharacterVoiceGroupId(b, t.CharacterVoiceGroupID)
	CharacterVoiceSubtitleExcelAddTlmid(b, tlmidOffset)
	CharacterVoiceSubtitleExcelAddDuration(b, t.Duration)
	CharacterVoiceSubtitleExcelAddDurationKr(b, t.DurationKr)
	CharacterVoiceSubtitleExcelAddSeparate(b, t.Separate)
	CharacterVoiceSubtitleExcelAddLocalizeKr(b, localizeKrOffset)
	CharacterVoiceSubtitleExcelAddLocalizeJp(b, localizeJpOffset)
	CharacterVoiceSubtitleExcelAddLocalizeTh(b, localizeThOffset)
	CharacterVoiceSubtitleExcelAddLocalizeTw(b, localizeTwOffset)
	CharacterVoiceSubtitleExcelAddLocalizeEn(b, localizeEnOffset)
	return CharacterVoiceSubtitleExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *CharacterVoiceSubtitleExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *CharacterVoiceSubtitleExcelDto) UnmarshalMessage(e *CharacterVoiceSubtitleExcel) error {
	t.LocalizeCvGroup = string(e.LocalizeCvGroup())
	t.CharacterVoiceGroupID = e.CharacterVoiceGroupId()
	t.Tlmid = string(e.Tlmid())
	t.Duration = e.Duration()
	t.DurationKr = e.DurationKr()
	t.Separate = e.Separate()
	t.LocalizeKr = string(e.LocalizeKr())
	t.LocalizeJp = string(e.LocalizeJp())
	t.LocalizeTh = string(e.LocalizeTh())
	t.LocalizeTw = string(e.LocalizeTw())
	t.LocalizeEn = string(e.LocalizeEn())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *CharacterVoiceSubtitleExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsCharacterVoiceSubtitleExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (CharacterVoiceSubtitleExcelDto) FlatDataName() string {
	return "CharacterVoiceSubtitleExcel"
}
