// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for FlatBuffers schema
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// LocalizeExcelDto represents a FlatBuffers table
type LocalizeExcelDto struct {
	fbsutils.FlatBuffer
	Key uint32 `json:"key"`
	Kr  string `json:"kr"`
	Jp  string `json:"jp"`
	Th  string `json:"th"`
	Tw  string `json:"tw"`
	En  string `json:"en"`
}

// MarshalModel marshals the struct into flatbuffers offset
func (t *LocalizeExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	__offset_kr := b.CreateString(fbsutils.Convert(t.Kr, t.FlatBuffer.TableKey))
	__offset_jp := b.CreateString(fbsutils.Convert(t.Jp, t.FlatBuffer.TableKey))
	__offset_th := b.CreateString(fbsutils.Convert(t.Th, t.FlatBuffer.TableKey))
	__offset_tw := b.CreateString(fbsutils.Convert(t.Tw, t.FlatBuffer.TableKey))
	__offset_en := b.CreateString(fbsutils.Convert(t.En, t.FlatBuffer.TableKey))
	LocalizeExcelStart(b)
	LocalizeExcelAddKey(b, fbsutils.Convert(t.Key, t.FlatBuffer.TableKey))
	LocalizeExcelAddKr(b, __offset_kr)
	LocalizeExcelAddJp(b, __offset_jp)
	LocalizeExcelAddTh(b, __offset_th)
	LocalizeExcelAddTw(b, __offset_tw)
	LocalizeExcelAddEn(b, __offset_en)
	return LocalizeExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer
func (t *LocalizeExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers buffer
func (t *LocalizeExcelDto) UnmarshalMessage(e *LocalizeExcel) error {
	t.Key = fbsutils.Convert(e.Key(), t.FlatBuffer.TableKey)
	t.Kr = fbsutils.Convert(string(e.Kr()), t.FlatBuffer.TableKey)
	t.Jp = fbsutils.Convert(string(e.Jp()), t.FlatBuffer.TableKey)
	t.Th = fbsutils.Convert(string(e.Th()), t.FlatBuffer.TableKey)
	t.Tw = fbsutils.Convert(string(e.Tw()), t.FlatBuffer.TableKey)
	t.En = fbsutils.Convert(string(e.En()), t.FlatBuffer.TableKey)
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer
func (t *LocalizeExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsLocalizeExcel(data, 0)
	err := t.UnmarshalMessage(root)
	if err != nil {
		return err
	}
	return nil
}

// Name returns the name of the flatbuffer table name
func (LocalizeExcelDto) FlatDataName() string {
	return "LocalizeExcel"
}
