// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// LocalizeGachaShopExcelDto represents a FlatBuffers table.
type LocalizeGachaShopExcelDto struct {
	fbsutils.FlatBuffer
	GachaShopID        int64  `json:"gacha_shop_id"`
	TabNameKr          string `json:"tab_name_kr"`
	TabNameJp          string `json:"tab_name_jp"`
	TabNameTh          string `json:"tab_name_th"`
	TabNameTw          string `json:"tab_name_tw"`
	TabNameEn          string `json:"tab_name_en"`
	TitleNameKr        string `json:"title_name_kr"`
	TitleNameJp        string `json:"title_name_jp"`
	TitleNameTh        string `json:"title_name_th"`
	TitleNameTw        string `json:"title_name_tw"`
	TitleNameEn        string `json:"title_name_en"`
	SubTitleKr         string `json:"sub_title_kr"`
	SubTitleJp         string `json:"sub_title_jp"`
	SubTitleTh         string `json:"sub_title_th"`
	SubTitleTw         string `json:"sub_title_tw"`
	SubTitleEn         string `json:"sub_title_en"`
	GachaDescriptionKr string `json:"gacha_description_kr"`
	GachaDescriptionJp string `json:"gacha_description_jp"`
	GachaDescriptionTh string `json:"gacha_description_th"`
	GachaDescriptionTw string `json:"gacha_description_tw"`
	GachaDescriptionEn string `json:"gacha_description_en"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *LocalizeGachaShopExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	tabNameKrOffset := b.CreateString(t.TabNameKr)
	tabNameJpOffset := b.CreateString(t.TabNameJp)
	tabNameThOffset := b.CreateString(t.TabNameTh)
	tabNameTwOffset := b.CreateString(t.TabNameTw)
	tabNameEnOffset := b.CreateString(t.TabNameEn)
	titleNameKrOffset := b.CreateString(t.TitleNameKr)
	titleNameJpOffset := b.CreateString(t.TitleNameJp)
	titleNameThOffset := b.CreateString(t.TitleNameTh)
	titleNameTwOffset := b.CreateString(t.TitleNameTw)
	titleNameEnOffset := b.CreateString(t.TitleNameEn)
	subTitleKrOffset := b.CreateString(t.SubTitleKr)
	subTitleJpOffset := b.CreateString(t.SubTitleJp)
	subTitleThOffset := b.CreateString(t.SubTitleTh)
	subTitleTwOffset := b.CreateString(t.SubTitleTw)
	subTitleEnOffset := b.CreateString(t.SubTitleEn)
	gachaDescriptionKrOffset := b.CreateString(t.GachaDescriptionKr)
	gachaDescriptionJpOffset := b.CreateString(t.GachaDescriptionJp)
	gachaDescriptionThOffset := b.CreateString(t.GachaDescriptionTh)
	gachaDescriptionTwOffset := b.CreateString(t.GachaDescriptionTw)
	gachaDescriptionEnOffset := b.CreateString(t.GachaDescriptionEn)
	LocalizeGachaShopExcelStart(b)
	LocalizeGachaShopExcelAddGachaShopId(b, t.GachaShopID)
	LocalizeGachaShopExcelAddTabNameKr(b, tabNameKrOffset)
	LocalizeGachaShopExcelAddTabNameJp(b, tabNameJpOffset)
	LocalizeGachaShopExcelAddTabNameTh(b, tabNameThOffset)
	LocalizeGachaShopExcelAddTabNameTw(b, tabNameTwOffset)
	LocalizeGachaShopExcelAddTabNameEn(b, tabNameEnOffset)
	LocalizeGachaShopExcelAddTitleNameKr(b, titleNameKrOffset)
	LocalizeGachaShopExcelAddTitleNameJp(b, titleNameJpOffset)
	LocalizeGachaShopExcelAddTitleNameTh(b, titleNameThOffset)
	LocalizeGachaShopExcelAddTitleNameTw(b, titleNameTwOffset)
	LocalizeGachaShopExcelAddTitleNameEn(b, titleNameEnOffset)
	LocalizeGachaShopExcelAddSubTitleKr(b, subTitleKrOffset)
	LocalizeGachaShopExcelAddSubTitleJp(b, subTitleJpOffset)
	LocalizeGachaShopExcelAddSubTitleTh(b, subTitleThOffset)
	LocalizeGachaShopExcelAddSubTitleTw(b, subTitleTwOffset)
	LocalizeGachaShopExcelAddSubTitleEn(b, subTitleEnOffset)
	LocalizeGachaShopExcelAddGachaDescriptionKr(b, gachaDescriptionKrOffset)
	LocalizeGachaShopExcelAddGachaDescriptionJp(b, gachaDescriptionJpOffset)
	LocalizeGachaShopExcelAddGachaDescriptionTh(b, gachaDescriptionThOffset)
	LocalizeGachaShopExcelAddGachaDescriptionTw(b, gachaDescriptionTwOffset)
	LocalizeGachaShopExcelAddGachaDescriptionEn(b, gachaDescriptionEnOffset)
	return LocalizeGachaShopExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *LocalizeGachaShopExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *LocalizeGachaShopExcelDto) UnmarshalMessage(e *LocalizeGachaShopExcel) error {
	t.GachaShopID = e.GachaShopId()
	t.TabNameKr = string(e.TabNameKr())
	t.TabNameJp = string(e.TabNameJp())
	t.TabNameTh = string(e.TabNameTh())
	t.TabNameTw = string(e.TabNameTw())
	t.TabNameEn = string(e.TabNameEn())
	t.TitleNameKr = string(e.TitleNameKr())
	t.TitleNameJp = string(e.TitleNameJp())
	t.TitleNameTh = string(e.TitleNameTh())
	t.TitleNameTw = string(e.TitleNameTw())
	t.TitleNameEn = string(e.TitleNameEn())
	t.SubTitleKr = string(e.SubTitleKr())
	t.SubTitleJp = string(e.SubTitleJp())
	t.SubTitleTh = string(e.SubTitleTh())
	t.SubTitleTw = string(e.SubTitleTw())
	t.SubTitleEn = string(e.SubTitleEn())
	t.GachaDescriptionKr = string(e.GachaDescriptionKr())
	t.GachaDescriptionJp = string(e.GachaDescriptionJp())
	t.GachaDescriptionTh = string(e.GachaDescriptionTh())
	t.GachaDescriptionTw = string(e.GachaDescriptionTw())
	t.GachaDescriptionEn = string(e.GachaDescriptionEn())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *LocalizeGachaShopExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsLocalizeGachaShopExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (LocalizeGachaShopExcelDto) FlatDataName() string {
	return "LocalizeGachaShopExcel"
}
