// Code generated by fbsgen. DO NOT EDIT.
// Package excel contains generated code for a FlatBuffers schema.
package excel

import (
	fbsutils "github.com/arisu-archive/bluearchive-fbs-utils"
	flatbuffers "github.com/google/flatbuffers/go"
)

// WebEventSeasonExcelDto represents a FlatBuffers table.
type WebEventSeasonExcelDto struct {
	fbsutils.FlatBuffer
	ID                    int64   `json:"id"`
	Enabled               bool    `json:"enabled"`
	IconOrder             int64   `json:"icon_order"`
	WebEventID            []int64 `json:"web_event_id"`
	IsFull                bool    `json:"is_full"`
	UseExternalBrowser    bool    `json:"use_external_browser"`
	StartDate             string  `json:"start_date"`
	EndDate               string  `json:"end_date"`
	LobbyBannerImage      string  `json:"lobby_banner_image"`
	PopupTitleLocalizeKey string  `json:"popup_title_localize_key"`
	StageEventURL         string  `json:"stage_event_url"`
	LiveEventURL          string  `json:"live_event_url"`
}

// MarshalModel marshals the struct into a FlatBuffers offset.
func (t *WebEventSeasonExcelDto) MarshalModel(b *flatbuffers.Builder) flatbuffers.UOffsetT {
	WebEventSeasonExcelStartWebEventIdVector(b, len(t.WebEventID))
	for i := len(t.WebEventID) - 1; i >= 0; i-- {
		b.PrependInt64(t.WebEventID[i])
	}
	webEventIDOffset := b.EndVector(len(t.WebEventID))
	startDateOffset := b.CreateString(t.StartDate)
	endDateOffset := b.CreateString(t.EndDate)
	lobbyBannerImageOffset := b.CreateString(t.LobbyBannerImage)
	popupTitleLocalizeKeyOffset := b.CreateString(t.PopupTitleLocalizeKey)
	stageEventURLOffset := b.CreateString(t.StageEventURL)
	liveEventURLOffset := b.CreateString(t.LiveEventURL)
	WebEventSeasonExcelStart(b)
	WebEventSeasonExcelAddId(b, t.ID)
	WebEventSeasonExcelAddEnabled(b, t.Enabled)
	WebEventSeasonExcelAddIconOrder(b, t.IconOrder)
	WebEventSeasonExcelAddWebEventId(b, webEventIDOffset)
	WebEventSeasonExcelAddIsFull(b, t.IsFull)
	WebEventSeasonExcelAddUseExternalBrowser(b, t.UseExternalBrowser)
	WebEventSeasonExcelAddStartDate(b, startDateOffset)
	WebEventSeasonExcelAddEndDate(b, endDateOffset)
	WebEventSeasonExcelAddLobbyBannerImage(b, lobbyBannerImageOffset)
	WebEventSeasonExcelAddPopupTitleLocalizeKey(b, popupTitleLocalizeKeyOffset)
	WebEventSeasonExcelAddStageEventUrl(b, stageEventURLOffset)
	WebEventSeasonExcelAddLiveEventUrl(b, liveEventURLOffset)
	return WebEventSeasonExcelEnd(b)
}

// Marshal marshals the struct into a FlatBuffers buffer.
func (t *WebEventSeasonExcelDto) Marshal() ([]byte, error) {
	b := flatbuffers.NewBuilder(0)
	b.Finish(t.MarshalModel(b))
	return b.FinishedBytes(), nil
}

// UnmarshalMessage unmarshals the struct from a FlatBuffers table.
func (t *WebEventSeasonExcelDto) UnmarshalMessage(e *WebEventSeasonExcel) error {
	t.ID = e.Id()
	t.Enabled = e.Enabled()
	t.IconOrder = e.IconOrder()
	t.WebEventID = make([]int64, e.WebEventIdLength())
	for i := 0; i < e.WebEventIdLength(); i++ {
		t.WebEventID[i] = e.WebEventId(i)
	}
	t.IsFull = e.IsFull()
	t.UseExternalBrowser = e.UseExternalBrowser()
	t.StartDate = string(e.StartDate())
	t.EndDate = string(e.EndDate())
	t.LobbyBannerImage = string(e.LobbyBannerImage())
	t.PopupTitleLocalizeKey = string(e.PopupTitleLocalizeKey())
	t.StageEventURL = string(e.StageEventUrl())
	t.LiveEventURL = string(e.LiveEventUrl())
	return nil
}

// Unmarshal unmarshals the struct from a FlatBuffers buffer.
func (t *WebEventSeasonExcelDto) Unmarshal(data []byte) error {
	root := GetRootAsWebEventSeasonExcel(data, 0)
	return t.UnmarshalMessage(root)
}

// FlatDataName returns the FlatBuffers table name.
func (WebEventSeasonExcelDto) FlatDataName() string {
	return "WebEventSeasonExcel"
}
