# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ConstCombatExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ConstCombatExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsConstCombatExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ConstCombatExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ConstCombatExcel
    def AccuracyConstA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def AccuracyConstB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def AccuracyConstC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def AccuracyConstD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def AimIkMaxDegree(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def AimIkMinDegree(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def AllowedMaxTimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def ArenaMinimumClearTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def AuraExitThresholdMargin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def BodyRotateSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def BuffIconBlinkTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def BulletTimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def ChampionRegenCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CheckCheaterMaxUseCostArena(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CheckCheaterMaxUseCostMultiFloorRaid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CheckCheaterMaxUseCostNonArena(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CriticalConstA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CriticalConstB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CriticalConstC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CriticalConstD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def CrowdControlFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def DefenceConstA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def DefenceConstB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(48))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def DefenceConstC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(50))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def DefenceConstD(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(52))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def DyingTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(54))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EchelonExtensionCostRegenRatio(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(56))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EchelonExtensionEchelonInitCommonCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(58))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EchelonExtensionEchelonMaxCommonCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(60))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EchelonExtensionEngageTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(62))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def EchelonExtensionEngageWithSupporterTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(64))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def EchelonExtensionVictoryTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(66))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def EchelonInitCommonCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(68))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EchelonMaxCommonCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(70))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EffectTeleportDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(72))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def EliminateRaidOpenScenarioId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(74))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def EmojiDefaultTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(76))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EnemyRegenCost(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(78))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def EngageTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(80))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def EngageWithSupporterTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(82))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def FastTimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(84))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def MaxGroupBuffLevel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(86))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def MaxRaidBossSkillSlot(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(88))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def MaxRaidTicketCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(90))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def MinimumClearLevelGap(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(92))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def MinimumClearTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(94))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def NormalTimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(96))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def PlayerRegenCostDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(98))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def PublicSpeechBubbleOffsetX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(100))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def PublicSpeechBubbleOffsetY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(102))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def PublicSpeechBubbleOffsetZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(104))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # ConstCombatExcel
    def RaidOpenScenarioId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(106))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def RaidRankingJumpMinimumWaitingTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(108))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def RandomAnimationOutput(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(110))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def ShowBufficonExSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(112))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def ShowBufficonExtraPassiveSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(114))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def ShowBufficonGroundPassiveSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(116))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def ShowBufficonLeaderSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(118))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def ShowBufficonPassiveSkill(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(120))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def ShowRaidListCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(122))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def SkillHandCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(124))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def SkillSlotCoolTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(126))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def SlowTimeScale(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(128))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def SummonedTeleportDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(130))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def SuppliesConditionStringId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(132))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def TimeLimitAlarm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(134))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def TimeLineActionRotateSpeed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(136))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def TsaInteractionDamageFactor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(138))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def UiDisplayDelayAfterSkillCutIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(140))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def UseInitialRangeForCoverMove(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(142))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ConstCombatExcel
    def VictoryInteractionRate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(144))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def VictoryTimelinePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(146))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ConstCombatExcel
    def Worldbossbattlehigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(148))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlehighAsia(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(150))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlehighGlobal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(152))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlehighNa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(154))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlehighTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(156))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def Worldbossbattlelittle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(158))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlelittleAsia(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(160))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlelittleGlobal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(162))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlelittleNa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(164))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlelittleTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(166))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def Worldbossbattlemiddle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(168))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlemiddleAsia(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(170))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlemiddleGlobal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(172))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlemiddleNa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(174))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattlemiddleTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(176))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def Worldbossbattleveryhigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(178))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattleveryhighAsia(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(180))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattleveryhighGlobal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(182))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattleveryhighNa(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(184))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldbossbattleveryhighTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(186))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldRaidAutoSyncTermSecond(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(188))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldRaidBossHpDecreaseTerm(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(190))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ConstCombatExcel
    def WorldRaidBossParcelReactionDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(192))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def ConstCombatExcelStart(builder):
    builder.StartObject(95)

def Start(builder):
    ConstCombatExcelStart(builder)

def ConstCombatExcelAddAccuracyConstA(builder, accuracyConstA):
    builder.PrependInt64Slot(0, accuracyConstA, 0)

def AddAccuracyConstA(builder, accuracyConstA):
    ConstCombatExcelAddAccuracyConstA(builder, accuracyConstA)

def ConstCombatExcelAddAccuracyConstB(builder, accuracyConstB):
    builder.PrependInt64Slot(1, accuracyConstB, 0)

def AddAccuracyConstB(builder, accuracyConstB):
    ConstCombatExcelAddAccuracyConstB(builder, accuracyConstB)

def ConstCombatExcelAddAccuracyConstC(builder, accuracyConstC):
    builder.PrependInt64Slot(2, accuracyConstC, 0)

def AddAccuracyConstC(builder, accuracyConstC):
    ConstCombatExcelAddAccuracyConstC(builder, accuracyConstC)

def ConstCombatExcelAddAccuracyConstD(builder, accuracyConstD):
    builder.PrependInt64Slot(3, accuracyConstD, 0)

def AddAccuracyConstD(builder, accuracyConstD):
    ConstCombatExcelAddAccuracyConstD(builder, accuracyConstD)

def ConstCombatExcelAddAimIkMaxDegree(builder, aimIkMaxDegree):
    builder.PrependFloat32Slot(4, aimIkMaxDegree, 0.0)

def AddAimIkMaxDegree(builder, aimIkMaxDegree):
    ConstCombatExcelAddAimIkMaxDegree(builder, aimIkMaxDegree)

def ConstCombatExcelAddAimIkMinDegree(builder, aimIkMinDegree):
    builder.PrependFloat32Slot(5, aimIkMinDegree, 0.0)

def AddAimIkMinDegree(builder, aimIkMinDegree):
    ConstCombatExcelAddAimIkMinDegree(builder, aimIkMinDegree)

def ConstCombatExcelAddAllowedMaxTimeScale(builder, allowedMaxTimeScale):
    builder.PrependInt64Slot(6, allowedMaxTimeScale, 0)

def AddAllowedMaxTimeScale(builder, allowedMaxTimeScale):
    ConstCombatExcelAddAllowedMaxTimeScale(builder, allowedMaxTimeScale)

def ConstCombatExcelAddArenaMinimumClearTime(builder, arenaMinimumClearTime):
    builder.PrependInt32Slot(7, arenaMinimumClearTime, 0)

def AddArenaMinimumClearTime(builder, arenaMinimumClearTime):
    ConstCombatExcelAddArenaMinimumClearTime(builder, arenaMinimumClearTime)

def ConstCombatExcelAddAuraExitThresholdMargin(builder, auraExitThresholdMargin):
    builder.PrependInt64Slot(8, auraExitThresholdMargin, 0)

def AddAuraExitThresholdMargin(builder, auraExitThresholdMargin):
    ConstCombatExcelAddAuraExitThresholdMargin(builder, auraExitThresholdMargin)

def ConstCombatExcelAddBodyRotateSpeed(builder, bodyRotateSpeed):
    builder.PrependInt64Slot(9, bodyRotateSpeed, 0)

def AddBodyRotateSpeed(builder, bodyRotateSpeed):
    ConstCombatExcelAddBodyRotateSpeed(builder, bodyRotateSpeed)

def ConstCombatExcelAddBuffIconBlinkTime(builder, buffIconBlinkTime):
    builder.PrependInt32Slot(10, buffIconBlinkTime, 0)

def AddBuffIconBlinkTime(builder, buffIconBlinkTime):
    ConstCombatExcelAddBuffIconBlinkTime(builder, buffIconBlinkTime)

def ConstCombatExcelAddBulletTimeScale(builder, bulletTimeScale):
    builder.PrependInt64Slot(11, bulletTimeScale, 0)

def AddBulletTimeScale(builder, bulletTimeScale):
    ConstCombatExcelAddBulletTimeScale(builder, bulletTimeScale)

def ConstCombatExcelAddChampionRegenCost(builder, championRegenCost):
    builder.PrependInt64Slot(12, championRegenCost, 0)

def AddChampionRegenCost(builder, championRegenCost):
    ConstCombatExcelAddChampionRegenCost(builder, championRegenCost)

def ConstCombatExcelAddCheckCheaterMaxUseCostArena(builder, checkCheaterMaxUseCostArena):
    builder.PrependInt32Slot(13, checkCheaterMaxUseCostArena, 0)

def AddCheckCheaterMaxUseCostArena(builder, checkCheaterMaxUseCostArena):
    ConstCombatExcelAddCheckCheaterMaxUseCostArena(builder, checkCheaterMaxUseCostArena)

def ConstCombatExcelAddCheckCheaterMaxUseCostMultiFloorRaid(builder, checkCheaterMaxUseCostMultiFloorRaid):
    builder.PrependInt32Slot(14, checkCheaterMaxUseCostMultiFloorRaid, 0)

def AddCheckCheaterMaxUseCostMultiFloorRaid(builder, checkCheaterMaxUseCostMultiFloorRaid):
    ConstCombatExcelAddCheckCheaterMaxUseCostMultiFloorRaid(builder, checkCheaterMaxUseCostMultiFloorRaid)

def ConstCombatExcelAddCheckCheaterMaxUseCostNonArena(builder, checkCheaterMaxUseCostNonArena):
    builder.PrependInt32Slot(15, checkCheaterMaxUseCostNonArena, 0)

def AddCheckCheaterMaxUseCostNonArena(builder, checkCheaterMaxUseCostNonArena):
    ConstCombatExcelAddCheckCheaterMaxUseCostNonArena(builder, checkCheaterMaxUseCostNonArena)

def ConstCombatExcelAddCriticalConstA(builder, criticalConstA):
    builder.PrependInt64Slot(16, criticalConstA, 0)

def AddCriticalConstA(builder, criticalConstA):
    ConstCombatExcelAddCriticalConstA(builder, criticalConstA)

def ConstCombatExcelAddCriticalConstB(builder, criticalConstB):
    builder.PrependInt64Slot(17, criticalConstB, 0)

def AddCriticalConstB(builder, criticalConstB):
    ConstCombatExcelAddCriticalConstB(builder, criticalConstB)

def ConstCombatExcelAddCriticalConstC(builder, criticalConstC):
    builder.PrependInt64Slot(18, criticalConstC, 0)

def AddCriticalConstC(builder, criticalConstC):
    ConstCombatExcelAddCriticalConstC(builder, criticalConstC)

def ConstCombatExcelAddCriticalConstD(builder, criticalConstD):
    builder.PrependInt64Slot(19, criticalConstD, 0)

def AddCriticalConstD(builder, criticalConstD):
    ConstCombatExcelAddCriticalConstD(builder, criticalConstD)

def ConstCombatExcelAddCrowdControlFactor(builder, crowdControlFactor):
    builder.PrependInt64Slot(20, crowdControlFactor, 0)

def AddCrowdControlFactor(builder, crowdControlFactor):
    ConstCombatExcelAddCrowdControlFactor(builder, crowdControlFactor)

def ConstCombatExcelAddDefenceConstA(builder, defenceConstA):
    builder.PrependInt64Slot(21, defenceConstA, 0)

def AddDefenceConstA(builder, defenceConstA):
    ConstCombatExcelAddDefenceConstA(builder, defenceConstA)

def ConstCombatExcelAddDefenceConstB(builder, defenceConstB):
    builder.PrependInt64Slot(22, defenceConstB, 0)

def AddDefenceConstB(builder, defenceConstB):
    ConstCombatExcelAddDefenceConstB(builder, defenceConstB)

def ConstCombatExcelAddDefenceConstC(builder, defenceConstC):
    builder.PrependInt64Slot(23, defenceConstC, 0)

def AddDefenceConstC(builder, defenceConstC):
    ConstCombatExcelAddDefenceConstC(builder, defenceConstC)

def ConstCombatExcelAddDefenceConstD(builder, defenceConstD):
    builder.PrependInt64Slot(24, defenceConstD, 0)

def AddDefenceConstD(builder, defenceConstD):
    ConstCombatExcelAddDefenceConstD(builder, defenceConstD)

def ConstCombatExcelAddDyingTime(builder, dyingTime):
    builder.PrependInt32Slot(25, dyingTime, 0)

def AddDyingTime(builder, dyingTime):
    ConstCombatExcelAddDyingTime(builder, dyingTime)

def ConstCombatExcelAddEchelonExtensionCostRegenRatio(builder, echelonExtensionCostRegenRatio):
    builder.PrependInt64Slot(26, echelonExtensionCostRegenRatio, 0)

def AddEchelonExtensionCostRegenRatio(builder, echelonExtensionCostRegenRatio):
    ConstCombatExcelAddEchelonExtensionCostRegenRatio(builder, echelonExtensionCostRegenRatio)

def ConstCombatExcelAddEchelonExtensionEchelonInitCommonCost(builder, echelonExtensionEchelonInitCommonCost):
    builder.PrependInt32Slot(27, echelonExtensionEchelonInitCommonCost, 0)

def AddEchelonExtensionEchelonInitCommonCost(builder, echelonExtensionEchelonInitCommonCost):
    ConstCombatExcelAddEchelonExtensionEchelonInitCommonCost(builder, echelonExtensionEchelonInitCommonCost)

def ConstCombatExcelAddEchelonExtensionEchelonMaxCommonCost(builder, echelonExtensionEchelonMaxCommonCost):
    builder.PrependInt32Slot(28, echelonExtensionEchelonMaxCommonCost, 0)

def AddEchelonExtensionEchelonMaxCommonCost(builder, echelonExtensionEchelonMaxCommonCost):
    ConstCombatExcelAddEchelonExtensionEchelonMaxCommonCost(builder, echelonExtensionEchelonMaxCommonCost)

def ConstCombatExcelAddEchelonExtensionEngageTimelinePath(builder, echelonExtensionEngageTimelinePath):
    builder.PrependUOffsetTRelativeSlot(29, flatbuffers.number_types.UOffsetTFlags.py_type(echelonExtensionEngageTimelinePath), 0)

def AddEchelonExtensionEngageTimelinePath(builder, echelonExtensionEngageTimelinePath):
    ConstCombatExcelAddEchelonExtensionEngageTimelinePath(builder, echelonExtensionEngageTimelinePath)

def ConstCombatExcelAddEchelonExtensionEngageWithSupporterTimelinePath(builder, echelonExtensionEngageWithSupporterTimelinePath):
    builder.PrependUOffsetTRelativeSlot(30, flatbuffers.number_types.UOffsetTFlags.py_type(echelonExtensionEngageWithSupporterTimelinePath), 0)

def AddEchelonExtensionEngageWithSupporterTimelinePath(builder, echelonExtensionEngageWithSupporterTimelinePath):
    ConstCombatExcelAddEchelonExtensionEngageWithSupporterTimelinePath(builder, echelonExtensionEngageWithSupporterTimelinePath)

def ConstCombatExcelAddEchelonExtensionVictoryTimelinePath(builder, echelonExtensionVictoryTimelinePath):
    builder.PrependUOffsetTRelativeSlot(31, flatbuffers.number_types.UOffsetTFlags.py_type(echelonExtensionVictoryTimelinePath), 0)

def AddEchelonExtensionVictoryTimelinePath(builder, echelonExtensionVictoryTimelinePath):
    ConstCombatExcelAddEchelonExtensionVictoryTimelinePath(builder, echelonExtensionVictoryTimelinePath)

def ConstCombatExcelAddEchelonInitCommonCost(builder, echelonInitCommonCost):
    builder.PrependInt32Slot(32, echelonInitCommonCost, 0)

def AddEchelonInitCommonCost(builder, echelonInitCommonCost):
    ConstCombatExcelAddEchelonInitCommonCost(builder, echelonInitCommonCost)

def ConstCombatExcelAddEchelonMaxCommonCost(builder, echelonMaxCommonCost):
    builder.PrependInt32Slot(33, echelonMaxCommonCost, 0)

def AddEchelonMaxCommonCost(builder, echelonMaxCommonCost):
    ConstCombatExcelAddEchelonMaxCommonCost(builder, echelonMaxCommonCost)

def ConstCombatExcelAddEffectTeleportDistance(builder, effectTeleportDistance):
    builder.PrependFloat32Slot(34, effectTeleportDistance, 0.0)

def AddEffectTeleportDistance(builder, effectTeleportDistance):
    ConstCombatExcelAddEffectTeleportDistance(builder, effectTeleportDistance)

def ConstCombatExcelAddEliminateRaidOpenScenarioId(builder, eliminateRaidOpenScenarioId):
    builder.PrependUOffsetTRelativeSlot(35, flatbuffers.number_types.UOffsetTFlags.py_type(eliminateRaidOpenScenarioId), 0)

def AddEliminateRaidOpenScenarioId(builder, eliminateRaidOpenScenarioId):
    ConstCombatExcelAddEliminateRaidOpenScenarioId(builder, eliminateRaidOpenScenarioId)

def ConstCombatExcelAddEmojiDefaultTime(builder, emojiDefaultTime):
    builder.PrependInt32Slot(36, emojiDefaultTime, 0)

def AddEmojiDefaultTime(builder, emojiDefaultTime):
    ConstCombatExcelAddEmojiDefaultTime(builder, emojiDefaultTime)

def ConstCombatExcelAddEnemyRegenCost(builder, enemyRegenCost):
    builder.PrependInt64Slot(37, enemyRegenCost, 0)

def AddEnemyRegenCost(builder, enemyRegenCost):
    ConstCombatExcelAddEnemyRegenCost(builder, enemyRegenCost)

def ConstCombatExcelAddEngageTimelinePath(builder, engageTimelinePath):
    builder.PrependUOffsetTRelativeSlot(38, flatbuffers.number_types.UOffsetTFlags.py_type(engageTimelinePath), 0)

def AddEngageTimelinePath(builder, engageTimelinePath):
    ConstCombatExcelAddEngageTimelinePath(builder, engageTimelinePath)

def ConstCombatExcelAddEngageWithSupporterTimelinePath(builder, engageWithSupporterTimelinePath):
    builder.PrependUOffsetTRelativeSlot(39, flatbuffers.number_types.UOffsetTFlags.py_type(engageWithSupporterTimelinePath), 0)

def AddEngageWithSupporterTimelinePath(builder, engageWithSupporterTimelinePath):
    ConstCombatExcelAddEngageWithSupporterTimelinePath(builder, engageWithSupporterTimelinePath)

def ConstCombatExcelAddFastTimeScale(builder, fastTimeScale):
    builder.PrependInt64Slot(40, fastTimeScale, 0)

def AddFastTimeScale(builder, fastTimeScale):
    ConstCombatExcelAddFastTimeScale(builder, fastTimeScale)

def ConstCombatExcelAddMaxGroupBuffLevel(builder, maxGroupBuffLevel):
    builder.PrependInt32Slot(41, maxGroupBuffLevel, 0)

def AddMaxGroupBuffLevel(builder, maxGroupBuffLevel):
    ConstCombatExcelAddMaxGroupBuffLevel(builder, maxGroupBuffLevel)

def ConstCombatExcelAddMaxRaidBossSkillSlot(builder, maxRaidBossSkillSlot):
    builder.PrependInt64Slot(42, maxRaidBossSkillSlot, 0)

def AddMaxRaidBossSkillSlot(builder, maxRaidBossSkillSlot):
    ConstCombatExcelAddMaxRaidBossSkillSlot(builder, maxRaidBossSkillSlot)

def ConstCombatExcelAddMaxRaidTicketCount(builder, maxRaidTicketCount):
    builder.PrependInt64Slot(43, maxRaidTicketCount, 0)

def AddMaxRaidTicketCount(builder, maxRaidTicketCount):
    ConstCombatExcelAddMaxRaidTicketCount(builder, maxRaidTicketCount)

def ConstCombatExcelAddMinimumClearLevelGap(builder, minimumClearLevelGap):
    builder.PrependInt32Slot(44, minimumClearLevelGap, 0)

def AddMinimumClearLevelGap(builder, minimumClearLevelGap):
    ConstCombatExcelAddMinimumClearLevelGap(builder, minimumClearLevelGap)

def ConstCombatExcelAddMinimumClearTime(builder, minimumClearTime):
    builder.PrependInt32Slot(45, minimumClearTime, 0)

def AddMinimumClearTime(builder, minimumClearTime):
    ConstCombatExcelAddMinimumClearTime(builder, minimumClearTime)

def ConstCombatExcelAddNormalTimeScale(builder, normalTimeScale):
    builder.PrependInt64Slot(46, normalTimeScale, 0)

def AddNormalTimeScale(builder, normalTimeScale):
    ConstCombatExcelAddNormalTimeScale(builder, normalTimeScale)

def ConstCombatExcelAddPlayerRegenCostDelay(builder, playerRegenCostDelay):
    builder.PrependInt64Slot(47, playerRegenCostDelay, 0)

def AddPlayerRegenCostDelay(builder, playerRegenCostDelay):
    ConstCombatExcelAddPlayerRegenCostDelay(builder, playerRegenCostDelay)

def ConstCombatExcelAddPublicSpeechBubbleOffsetX(builder, publicSpeechBubbleOffsetX):
    builder.PrependFloat32Slot(48, publicSpeechBubbleOffsetX, 0.0)

def AddPublicSpeechBubbleOffsetX(builder, publicSpeechBubbleOffsetX):
    ConstCombatExcelAddPublicSpeechBubbleOffsetX(builder, publicSpeechBubbleOffsetX)

def ConstCombatExcelAddPublicSpeechBubbleOffsetY(builder, publicSpeechBubbleOffsetY):
    builder.PrependFloat32Slot(49, publicSpeechBubbleOffsetY, 0.0)

def AddPublicSpeechBubbleOffsetY(builder, publicSpeechBubbleOffsetY):
    ConstCombatExcelAddPublicSpeechBubbleOffsetY(builder, publicSpeechBubbleOffsetY)

def ConstCombatExcelAddPublicSpeechBubbleOffsetZ(builder, publicSpeechBubbleOffsetZ):
    builder.PrependFloat32Slot(50, publicSpeechBubbleOffsetZ, 0.0)

def AddPublicSpeechBubbleOffsetZ(builder, publicSpeechBubbleOffsetZ):
    ConstCombatExcelAddPublicSpeechBubbleOffsetZ(builder, publicSpeechBubbleOffsetZ)

def ConstCombatExcelAddRaidOpenScenarioId(builder, raidOpenScenarioId):
    builder.PrependUOffsetTRelativeSlot(51, flatbuffers.number_types.UOffsetTFlags.py_type(raidOpenScenarioId), 0)

def AddRaidOpenScenarioId(builder, raidOpenScenarioId):
    ConstCombatExcelAddRaidOpenScenarioId(builder, raidOpenScenarioId)

def ConstCombatExcelAddRaidRankingJumpMinimumWaitingTime(builder, raidRankingJumpMinimumWaitingTime):
    builder.PrependInt64Slot(52, raidRankingJumpMinimumWaitingTime, 0)

def AddRaidRankingJumpMinimumWaitingTime(builder, raidRankingJumpMinimumWaitingTime):
    ConstCombatExcelAddRaidRankingJumpMinimumWaitingTime(builder, raidRankingJumpMinimumWaitingTime)

def ConstCombatExcelAddRandomAnimationOutput(builder, randomAnimationOutput):
    builder.PrependInt64Slot(53, randomAnimationOutput, 0)

def AddRandomAnimationOutput(builder, randomAnimationOutput):
    ConstCombatExcelAddRandomAnimationOutput(builder, randomAnimationOutput)

def ConstCombatExcelAddShowBufficonExSkill(builder, showBufficonExSkill):
    builder.PrependBoolSlot(54, showBufficonExSkill, 0)

def AddShowBufficonExSkill(builder, showBufficonExSkill):
    ConstCombatExcelAddShowBufficonExSkill(builder, showBufficonExSkill)

def ConstCombatExcelAddShowBufficonExtraPassiveSkill(builder, showBufficonExtraPassiveSkill):
    builder.PrependBoolSlot(55, showBufficonExtraPassiveSkill, 0)

def AddShowBufficonExtraPassiveSkill(builder, showBufficonExtraPassiveSkill):
    ConstCombatExcelAddShowBufficonExtraPassiveSkill(builder, showBufficonExtraPassiveSkill)

def ConstCombatExcelAddShowBufficonGroundPassiveSkill(builder, showBufficonGroundPassiveSkill):
    builder.PrependBoolSlot(56, showBufficonGroundPassiveSkill, 0)

def AddShowBufficonGroundPassiveSkill(builder, showBufficonGroundPassiveSkill):
    ConstCombatExcelAddShowBufficonGroundPassiveSkill(builder, showBufficonGroundPassiveSkill)

def ConstCombatExcelAddShowBufficonLeaderSkill(builder, showBufficonLeaderSkill):
    builder.PrependBoolSlot(57, showBufficonLeaderSkill, 0)

def AddShowBufficonLeaderSkill(builder, showBufficonLeaderSkill):
    ConstCombatExcelAddShowBufficonLeaderSkill(builder, showBufficonLeaderSkill)

def ConstCombatExcelAddShowBufficonPassiveSkill(builder, showBufficonPassiveSkill):
    builder.PrependBoolSlot(58, showBufficonPassiveSkill, 0)

def AddShowBufficonPassiveSkill(builder, showBufficonPassiveSkill):
    ConstCombatExcelAddShowBufficonPassiveSkill(builder, showBufficonPassiveSkill)

def ConstCombatExcelAddShowRaidListCount(builder, showRaidListCount):
    builder.PrependInt32Slot(59, showRaidListCount, 0)

def AddShowRaidListCount(builder, showRaidListCount):
    ConstCombatExcelAddShowRaidListCount(builder, showRaidListCount)

def ConstCombatExcelAddSkillHandCount(builder, skillHandCount):
    builder.PrependInt32Slot(60, skillHandCount, 0)

def AddSkillHandCount(builder, skillHandCount):
    ConstCombatExcelAddSkillHandCount(builder, skillHandCount)

def ConstCombatExcelAddSkillSlotCoolTime(builder, skillSlotCoolTime):
    builder.PrependInt64Slot(61, skillSlotCoolTime, 0)

def AddSkillSlotCoolTime(builder, skillSlotCoolTime):
    ConstCombatExcelAddSkillSlotCoolTime(builder, skillSlotCoolTime)

def ConstCombatExcelAddSlowTimeScale(builder, slowTimeScale):
    builder.PrependInt64Slot(62, slowTimeScale, 0)

def AddSlowTimeScale(builder, slowTimeScale):
    ConstCombatExcelAddSlowTimeScale(builder, slowTimeScale)

def ConstCombatExcelAddSummonedTeleportDistance(builder, summonedTeleportDistance):
    builder.PrependInt64Slot(63, summonedTeleportDistance, 0)

def AddSummonedTeleportDistance(builder, summonedTeleportDistance):
    ConstCombatExcelAddSummonedTeleportDistance(builder, summonedTeleportDistance)

def ConstCombatExcelAddSuppliesConditionStringId(builder, suppliesConditionStringId):
    builder.PrependUOffsetTRelativeSlot(64, flatbuffers.number_types.UOffsetTFlags.py_type(suppliesConditionStringId), 0)

def AddSuppliesConditionStringId(builder, suppliesConditionStringId):
    ConstCombatExcelAddSuppliesConditionStringId(builder, suppliesConditionStringId)

def ConstCombatExcelAddTimeLimitAlarm(builder, timeLimitAlarm):
    builder.PrependInt64Slot(65, timeLimitAlarm, 0)

def AddTimeLimitAlarm(builder, timeLimitAlarm):
    ConstCombatExcelAddTimeLimitAlarm(builder, timeLimitAlarm)

def ConstCombatExcelAddTimeLineActionRotateSpeed(builder, timeLineActionRotateSpeed):
    builder.PrependInt64Slot(66, timeLineActionRotateSpeed, 0)

def AddTimeLineActionRotateSpeed(builder, timeLineActionRotateSpeed):
    ConstCombatExcelAddTimeLineActionRotateSpeed(builder, timeLineActionRotateSpeed)

def ConstCombatExcelAddTsaInteractionDamageFactor(builder, tsaInteractionDamageFactor):
    builder.PrependInt64Slot(67, tsaInteractionDamageFactor, 0)

def AddTsaInteractionDamageFactor(builder, tsaInteractionDamageFactor):
    ConstCombatExcelAddTsaInteractionDamageFactor(builder, tsaInteractionDamageFactor)

def ConstCombatExcelAddUiDisplayDelayAfterSkillCutIn(builder, uiDisplayDelayAfterSkillCutIn):
    builder.PrependInt64Slot(68, uiDisplayDelayAfterSkillCutIn, 0)

def AddUiDisplayDelayAfterSkillCutIn(builder, uiDisplayDelayAfterSkillCutIn):
    ConstCombatExcelAddUiDisplayDelayAfterSkillCutIn(builder, uiDisplayDelayAfterSkillCutIn)

def ConstCombatExcelAddUseInitialRangeForCoverMove(builder, useInitialRangeForCoverMove):
    builder.PrependBoolSlot(69, useInitialRangeForCoverMove, 0)

def AddUseInitialRangeForCoverMove(builder, useInitialRangeForCoverMove):
    ConstCombatExcelAddUseInitialRangeForCoverMove(builder, useInitialRangeForCoverMove)

def ConstCombatExcelAddVictoryInteractionRate(builder, victoryInteractionRate):
    builder.PrependInt64Slot(70, victoryInteractionRate, 0)

def AddVictoryInteractionRate(builder, victoryInteractionRate):
    ConstCombatExcelAddVictoryInteractionRate(builder, victoryInteractionRate)

def ConstCombatExcelAddVictoryTimelinePath(builder, victoryTimelinePath):
    builder.PrependUOffsetTRelativeSlot(71, flatbuffers.number_types.UOffsetTFlags.py_type(victoryTimelinePath), 0)

def AddVictoryTimelinePath(builder, victoryTimelinePath):
    ConstCombatExcelAddVictoryTimelinePath(builder, victoryTimelinePath)

def ConstCombatExcelAddWorldbossbattlehigh(builder, worldbossbattlehigh):
    builder.PrependInt64Slot(72, worldbossbattlehigh, 0)

def AddWorldbossbattlehigh(builder, worldbossbattlehigh):
    ConstCombatExcelAddWorldbossbattlehigh(builder, worldbossbattlehigh)

def ConstCombatExcelAddWorldbossbattlehighAsia(builder, worldbossbattlehighAsia):
    builder.PrependInt64Slot(73, worldbossbattlehighAsia, 0)

def AddWorldbossbattlehighAsia(builder, worldbossbattlehighAsia):
    ConstCombatExcelAddWorldbossbattlehighAsia(builder, worldbossbattlehighAsia)

def ConstCombatExcelAddWorldbossbattlehighGlobal(builder, worldbossbattlehighGlobal):
    builder.PrependInt64Slot(74, worldbossbattlehighGlobal, 0)

def AddWorldbossbattlehighGlobal(builder, worldbossbattlehighGlobal):
    ConstCombatExcelAddWorldbossbattlehighGlobal(builder, worldbossbattlehighGlobal)

def ConstCombatExcelAddWorldbossbattlehighNa(builder, worldbossbattlehighNa):
    builder.PrependInt64Slot(75, worldbossbattlehighNa, 0)

def AddWorldbossbattlehighNa(builder, worldbossbattlehighNa):
    ConstCombatExcelAddWorldbossbattlehighNa(builder, worldbossbattlehighNa)

def ConstCombatExcelAddWorldbossbattlehighTw(builder, worldbossbattlehighTw):
    builder.PrependInt64Slot(76, worldbossbattlehighTw, 0)

def AddWorldbossbattlehighTw(builder, worldbossbattlehighTw):
    ConstCombatExcelAddWorldbossbattlehighTw(builder, worldbossbattlehighTw)

def ConstCombatExcelAddWorldbossbattlelittle(builder, worldbossbattlelittle):
    builder.PrependInt64Slot(77, worldbossbattlelittle, 0)

def AddWorldbossbattlelittle(builder, worldbossbattlelittle):
    ConstCombatExcelAddWorldbossbattlelittle(builder, worldbossbattlelittle)

def ConstCombatExcelAddWorldbossbattlelittleAsia(builder, worldbossbattlelittleAsia):
    builder.PrependInt64Slot(78, worldbossbattlelittleAsia, 0)

def AddWorldbossbattlelittleAsia(builder, worldbossbattlelittleAsia):
    ConstCombatExcelAddWorldbossbattlelittleAsia(builder, worldbossbattlelittleAsia)

def ConstCombatExcelAddWorldbossbattlelittleGlobal(builder, worldbossbattlelittleGlobal):
    builder.PrependInt64Slot(79, worldbossbattlelittleGlobal, 0)

def AddWorldbossbattlelittleGlobal(builder, worldbossbattlelittleGlobal):
    ConstCombatExcelAddWorldbossbattlelittleGlobal(builder, worldbossbattlelittleGlobal)

def ConstCombatExcelAddWorldbossbattlelittleNa(builder, worldbossbattlelittleNa):
    builder.PrependInt64Slot(80, worldbossbattlelittleNa, 0)

def AddWorldbossbattlelittleNa(builder, worldbossbattlelittleNa):
    ConstCombatExcelAddWorldbossbattlelittleNa(builder, worldbossbattlelittleNa)

def ConstCombatExcelAddWorldbossbattlelittleTw(builder, worldbossbattlelittleTw):
    builder.PrependInt64Slot(81, worldbossbattlelittleTw, 0)

def AddWorldbossbattlelittleTw(builder, worldbossbattlelittleTw):
    ConstCombatExcelAddWorldbossbattlelittleTw(builder, worldbossbattlelittleTw)

def ConstCombatExcelAddWorldbossbattlemiddle(builder, worldbossbattlemiddle):
    builder.PrependInt64Slot(82, worldbossbattlemiddle, 0)

def AddWorldbossbattlemiddle(builder, worldbossbattlemiddle):
    ConstCombatExcelAddWorldbossbattlemiddle(builder, worldbossbattlemiddle)

def ConstCombatExcelAddWorldbossbattlemiddleAsia(builder, worldbossbattlemiddleAsia):
    builder.PrependInt64Slot(83, worldbossbattlemiddleAsia, 0)

def AddWorldbossbattlemiddleAsia(builder, worldbossbattlemiddleAsia):
    ConstCombatExcelAddWorldbossbattlemiddleAsia(builder, worldbossbattlemiddleAsia)

def ConstCombatExcelAddWorldbossbattlemiddleGlobal(builder, worldbossbattlemiddleGlobal):
    builder.PrependInt64Slot(84, worldbossbattlemiddleGlobal, 0)

def AddWorldbossbattlemiddleGlobal(builder, worldbossbattlemiddleGlobal):
    ConstCombatExcelAddWorldbossbattlemiddleGlobal(builder, worldbossbattlemiddleGlobal)

def ConstCombatExcelAddWorldbossbattlemiddleNa(builder, worldbossbattlemiddleNa):
    builder.PrependInt64Slot(85, worldbossbattlemiddleNa, 0)

def AddWorldbossbattlemiddleNa(builder, worldbossbattlemiddleNa):
    ConstCombatExcelAddWorldbossbattlemiddleNa(builder, worldbossbattlemiddleNa)

def ConstCombatExcelAddWorldbossbattlemiddleTw(builder, worldbossbattlemiddleTw):
    builder.PrependInt64Slot(86, worldbossbattlemiddleTw, 0)

def AddWorldbossbattlemiddleTw(builder, worldbossbattlemiddleTw):
    ConstCombatExcelAddWorldbossbattlemiddleTw(builder, worldbossbattlemiddleTw)

def ConstCombatExcelAddWorldbossbattleveryhigh(builder, worldbossbattleveryhigh):
    builder.PrependInt64Slot(87, worldbossbattleveryhigh, 0)

def AddWorldbossbattleveryhigh(builder, worldbossbattleveryhigh):
    ConstCombatExcelAddWorldbossbattleveryhigh(builder, worldbossbattleveryhigh)

def ConstCombatExcelAddWorldbossbattleveryhighAsia(builder, worldbossbattleveryhighAsia):
    builder.PrependInt64Slot(88, worldbossbattleveryhighAsia, 0)

def AddWorldbossbattleveryhighAsia(builder, worldbossbattleveryhighAsia):
    ConstCombatExcelAddWorldbossbattleveryhighAsia(builder, worldbossbattleveryhighAsia)

def ConstCombatExcelAddWorldbossbattleveryhighGlobal(builder, worldbossbattleveryhighGlobal):
    builder.PrependInt64Slot(89, worldbossbattleveryhighGlobal, 0)

def AddWorldbossbattleveryhighGlobal(builder, worldbossbattleveryhighGlobal):
    ConstCombatExcelAddWorldbossbattleveryhighGlobal(builder, worldbossbattleveryhighGlobal)

def ConstCombatExcelAddWorldbossbattleveryhighNa(builder, worldbossbattleveryhighNa):
    builder.PrependInt64Slot(90, worldbossbattleveryhighNa, 0)

def AddWorldbossbattleveryhighNa(builder, worldbossbattleveryhighNa):
    ConstCombatExcelAddWorldbossbattleveryhighNa(builder, worldbossbattleveryhighNa)

def ConstCombatExcelAddWorldbossbattleveryhighTw(builder, worldbossbattleveryhighTw):
    builder.PrependInt64Slot(91, worldbossbattleveryhighTw, 0)

def AddWorldbossbattleveryhighTw(builder, worldbossbattleveryhighTw):
    ConstCombatExcelAddWorldbossbattleveryhighTw(builder, worldbossbattleveryhighTw)

def ConstCombatExcelAddWorldRaidAutoSyncTermSecond(builder, worldRaidAutoSyncTermSecond):
    builder.PrependInt64Slot(92, worldRaidAutoSyncTermSecond, 0)

def AddWorldRaidAutoSyncTermSecond(builder, worldRaidAutoSyncTermSecond):
    ConstCombatExcelAddWorldRaidAutoSyncTermSecond(builder, worldRaidAutoSyncTermSecond)

def ConstCombatExcelAddWorldRaidBossHpDecreaseTerm(builder, worldRaidBossHpDecreaseTerm):
    builder.PrependInt64Slot(93, worldRaidBossHpDecreaseTerm, 0)

def AddWorldRaidBossHpDecreaseTerm(builder, worldRaidBossHpDecreaseTerm):
    ConstCombatExcelAddWorldRaidBossHpDecreaseTerm(builder, worldRaidBossHpDecreaseTerm)

def ConstCombatExcelAddWorldRaidBossParcelReactionDelay(builder, worldRaidBossParcelReactionDelay):
    builder.PrependInt64Slot(94, worldRaidBossParcelReactionDelay, 0)

def AddWorldRaidBossParcelReactionDelay(builder, worldRaidBossParcelReactionDelay):
    ConstCombatExcelAddWorldRaidBossParcelReactionDelay(builder, worldRaidBossParcelReactionDelay)

def ConstCombatExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return ConstCombatExcelEnd(builder)
