# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldSeasonExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldSeasonExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldSeasonExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldSeasonExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldSeasonExcel
    def CharacterIconPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def EndDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def EntryDateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def InstantEntryDateId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def LobbyBgmChangeStageId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # FieldSeasonExcel
    def MasteryImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def StartDate(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FieldSeasonExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def FieldSeasonExcelStart(builder): builder.StartObject(9)
def Start(builder):
    return FieldSeasonExcelStart(builder)
def FieldSeasonExcelAddCharacterIconPath(builder, characterIconPath): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(characterIconPath), 0)
def AddCharacterIconPath(builder, characterIconPath):
    return FieldSeasonExcelAddCharacterIconPath(builder, characterIconPath)
def FieldSeasonExcelAddEndDate(builder, endDate): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(endDate), 0)
def AddEndDate(builder, endDate):
    return FieldSeasonExcelAddEndDate(builder, endDate)
def FieldSeasonExcelAddEntryDateId(builder, entryDateId): builder.PrependInt64Slot(2, entryDateId, 0)
def AddEntryDateId(builder, entryDateId):
    return FieldSeasonExcelAddEntryDateId(builder, entryDateId)
def FieldSeasonExcelAddEventContentId(builder, eventContentId): builder.PrependInt64Slot(3, eventContentId, 0)
def AddEventContentId(builder, eventContentId):
    return FieldSeasonExcelAddEventContentId(builder, eventContentId)
def FieldSeasonExcelAddInstantEntryDateId(builder, instantEntryDateId): builder.PrependInt64Slot(4, instantEntryDateId, 0)
def AddInstantEntryDateId(builder, instantEntryDateId):
    return FieldSeasonExcelAddInstantEntryDateId(builder, instantEntryDateId)
def FieldSeasonExcelAddLobbyBgmChangeStageId(builder, lobbyBgmChangeStageId): builder.PrependInt64Slot(5, lobbyBgmChangeStageId, 0)
def AddLobbyBgmChangeStageId(builder, lobbyBgmChangeStageId):
    return FieldSeasonExcelAddLobbyBgmChangeStageId(builder, lobbyBgmChangeStageId)
def FieldSeasonExcelAddMasteryImagePath(builder, masteryImagePath): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(masteryImagePath), 0)
def AddMasteryImagePath(builder, masteryImagePath):
    return FieldSeasonExcelAddMasteryImagePath(builder, masteryImagePath)
def FieldSeasonExcelAddStartDate(builder, startDate): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(startDate), 0)
def AddStartDate(builder, startDate):
    return FieldSeasonExcelAddStartDate(builder, startDate)
def FieldSeasonExcelAddUniqueId(builder, uniqueId): builder.PrependInt64Slot(8, uniqueId, 0)
def AddUniqueId(builder, uniqueId):
    return FieldSeasonExcelAddUniqueId(builder, uniqueId)
def FieldSeasonExcelEnd(builder): return builder.EndObject()
def End(builder):
    return FieldSeasonExcelEnd(builder)