# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TacticSimulatorSettingExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TacticSimulatorSettingExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTacticSimulatorSettingExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TacticSimulatorSettingExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TacticSimulatorSettingExcel
    def GroundId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticSimulatorSettingExcel
    def GetExp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticSimulatorSettingExcel
    def GetStarGrade(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # TacticSimulatorSettingExcel
    def Equipment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def TacticSimulatorSettingExcelStart(builder):
    builder.StartObject(4)

def Start(builder):
    TacticSimulatorSettingExcelStart(builder)

def TacticSimulatorSettingExcelAddGroundId(builder, groundId):
    builder.PrependInt64Slot(0, groundId, 0)

def AddGroundId(builder, groundId):
    TacticSimulatorSettingExcelAddGroundId(builder, groundId)

def TacticSimulatorSettingExcelAddGetExp(builder, getExp):
    builder.PrependInt64Slot(1, getExp, 0)

def AddGetExp(builder, getExp):
    TacticSimulatorSettingExcelAddGetExp(builder, getExp)

def TacticSimulatorSettingExcelAddGetStarGrade(builder, getStarGrade):
    builder.PrependInt64Slot(2, getStarGrade, 0)

def AddGetStarGrade(builder, getStarGrade):
    TacticSimulatorSettingExcelAddGetStarGrade(builder, getStarGrade)

def TacticSimulatorSettingExcelAddEquipment(builder, equipment):
    builder.PrependInt64Slot(3, equipment, 0)

def AddEquipment(builder, equipment):
    TacticSimulatorSettingExcelAddEquipment(builder, equipment)

def TacticSimulatorSettingExcelEnd(builder):
    return builder.EndObject()

def End(builder):
    return TacticSimulatorSettingExcelEnd(builder)
