# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceSkillUseExcelTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceSkillUseExcelTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceSkillUseExcelTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VoiceSkillUseExcelTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceSkillUseExcelTable
    def DataList(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from FlatData.VoiceSkillUseExcel import VoiceSkillUseExcel
            obj = VoiceSkillUseExcel()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VoiceSkillUseExcelTable
    def DataListLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VoiceSkillUseExcelTable
    def DataListIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def VoiceSkillUseExcelTableStart(builder):
    builder.StartObject(1)

def Start(builder):
    VoiceSkillUseExcelTableStart(builder)

def VoiceSkillUseExcelTableAddDataList(builder, dataList):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(dataList), 0)

def AddDataList(builder, dataList):
    VoiceSkillUseExcelTableAddDataList(builder, dataList)

def VoiceSkillUseExcelTableStartDataListVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDataListVector(builder, numElems):
    return VoiceSkillUseExcelTableStartDataListVector(builder, numElems)

def VoiceSkillUseExcelTableEnd(builder):
    return builder.EndObject()

def End(builder):
    return VoiceSkillUseExcelTableEnd(builder)

import FlatData.VoiceSkillUseExcel
try:
    from typing import List
except:
    pass

class VoiceSkillUseExcelTableT(object):

    # VoiceSkillUseExcelTableT
    def __init__(
        self,
        dataList = None,
    ):
        self.dataList = dataList  # type: Optional[List[FlatData.VoiceSkillUseExcel.VoiceSkillUseExcelT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        voiceSkillUseExcelTable = VoiceSkillUseExcelTable()
        voiceSkillUseExcelTable.Init(buf, pos)
        return cls.InitFromObj(voiceSkillUseExcelTable)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, voiceSkillUseExcelTable):
        x = VoiceSkillUseExcelTableT()
        x._UnPack(voiceSkillUseExcelTable)
        return x

    # VoiceSkillUseExcelTableT
    def _UnPack(self, voiceSkillUseExcelTable):
        if voiceSkillUseExcelTable is None:
            return
        if not voiceSkillUseExcelTable.DataListIsNone():
            self.dataList = []
            for i in range(voiceSkillUseExcelTable.DataListLength()):
                if voiceSkillUseExcelTable.DataList(i) is None:
                    self.dataList.append(None)
                else:
                    voiceSkillUseExcel_ = FlatData.VoiceSkillUseExcel.VoiceSkillUseExcelT.InitFromObj(voiceSkillUseExcelTable.DataList(i))
                    self.dataList.append(voiceSkillUseExcel_)

    # VoiceSkillUseExcelTableT
    def Pack(self, builder):
        if self.dataList is not None:
            dataListlist = []
            for i in range(len(self.dataList)):
                dataListlist.append(self.dataList[i].Pack(builder))
            VoiceSkillUseExcelTableStartDataListVector(builder, len(self.dataList))
            for i in reversed(range(len(self.dataList))):
                builder.PrependUOffsetTRelative(dataListlist[i])
            dataList = builder.EndVector()
        VoiceSkillUseExcelTableStart(builder)
        if self.dataList is not None:
            VoiceSkillUseExcelTableAddDataList(builder, dataList)
        voiceSkillUseExcelTable = VoiceSkillUseExcelTableEnd(builder)
        return voiceSkillUseExcelTable

# arona-flatbuffer: object-api conversion
from FlatData._conversion import install_object_api as _install_object_api
_install_object_api(VoiceSkillUseExcelTableT, 'VoiceSkillUseExcelTable', ())
